### ISSUE TITLE
Please add Centos Stream to the images

### ISSUE THREAD

**Issue by raider700** [lxc/lxc-ci#103]
Hello,

can you add Centos Stream, the rolling release of Centos, to the Centos images?

Informations about Centos Stream:
* https://www.redhat.com/en/blog/transforming-development-experience-within-centos
* https://wiki.centos.org/Manuals/ReleaseNotes/CentOSStream#Presenting_CentOS_Stream

The next RedHat EL 8 Minor Versions will be based on Centos Stream.
There is also the option to get upstream versions faster.

Kindly regards,
Raider700

**Comment by stgraber** [comment]
@monstermunchkin can you take a quick look when you have some time?
I don't know if they produce the artifacts that we need for distrobuilder.

**Comment by monstermunchkin** [comment]
#104 resolves this issue.
