### ISSUE TITLE
Alpine edge images target wrong repo

### ISSUE THREAD

**Issue by FlyingWombat** [lxc/lxc-ci#107]
The images for Alpine edge target the 'v3.8' repos, instead of the 'edge' repos.

## Steps
1. `lxc launch images:alpine/edge/amd64 test`
1. `lxc exec test ash`
1. `cat /etc/apk/repositories`
```
http://dl-cdn.alpinelinux.org/alpine/v3.8/main
http://dl-cdn.alpinelinux.org/alpine/v3.8/community
```
It should be:
```
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
```
It's not just that the URL's are wrong, the base packages installed are from v3.8 too.

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by monstermunchkin** [comment]
> It's not just that the URL's are wrong, the base packages installed are from v3.8 too.

The repo URLs have been fixed. There are no edge base packages, see [here](http://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/). Our current implementation uses 3.8 as its base, but you can change that by adding `-o source.same_as=3.9` when running distrobuilder.
