### ISSUE TITLE
Question about the Ubuntu 16.04 xenial images

### ISSUE THREAD

**Issue by zeroware** [lxc/lxc-ci#11]
Hello,

I was wondering why the images for Ubuntu 16.04 are way lighter than the one provided by the remote `https://cloud-images.ubuntu.com/releases` ?
I can see for example that the `snapd` daemon is not included. 

Thanks,

**Comment by stgraber** [comment]
The community images are just a minimal debootstrap of Ubuntu + ssh and vim.

The images at cloud-images.ubuntu.com are full Ubuntu cloud images, coming with all the usual server tools.
