### ISSUE TITLE
Opensuse Leap images

### ISSUE THREAD

**Issue by mabes** [lxc/lxc-ci#12]
Are there any blockers to releasing Opensuse 42.1 and 42.2 images ?

**Comment by hwoarang** [comment]
I also e-mailed the list a few days ago (although my e-mail is still awaiting approval) to ask about Leap 42.3

**Comment by stgraber** [comment]
I've added 42.3 to Jenkins. So far neither 42.2 nor 42.3 are building due to broken IPv6 on the opensuse mirror, but hopefully that'll get fixed soon.
