### ISSUE TITLE
lxc-fedora-template CI job is failing

### ISSUE THREAD

**Issue by ganto** [lxc/lxc-ci#13]
Since merging the new `lxc-fedora` template from lxc/lxc#1371 all builds for the `fedora` download image are failing. See https://jenkins.linuxcontainers.org/job/lxc-template-fedora/. This should be fixed:

**Reason:**
- [Fedora 22](https://jenkins.linuxcontainers.org/job/lxc-template-fedora/arch=amd64,release=22,restrict=lxc-priv,variant=default/1452/consoleText): Not supported anymore by upstream, therefore aborted by `lxc-fedora` template:
```
 ==> Executing: "env root_password=root /usr/share/lxc/templates/lxc-fedora --path /build/containers/LXC_NAME --rootfs /build/containers/LXC_NAME/rootfs --name LXC_NAME -R 22 -a x86_64" in /
Error: Fedora release 22 is not supported. Set -R at least to 24.
``` 
- [Fedora 23](https://jenkins.linuxcontainers.org/job/lxc-template-fedora/arch=amd64,release=23,restrict=lxc-priv,variant=default/1452/consoleText): Not supported anymore by upstream, therefore aborted by `lxc-fedora` template:
```
 ==> Executing: "env root_password=root /usr/share/lxc/templates/lxc-fedora --path /build/containers/LXC_NAME --rootfs /build/containers/LXC_NAME/rootfs --name LXC_NAME -R 23 -a x86_64" in /
Error: Fedora release 23 is not supported. Set -R at least to 24.
``` 
- [Fedora 24](https://jenkins.linuxcontainers.org/job/lxc-template-fedora/arch=amd64,release=24,restrict=lxc-priv,variant=default/1452/consoleText): Failed to query mirrorlist in [get_mirrors()](https://github.com/lxc/lxc/blob/master/templates/lxc-fedora.in#L667) for a valid repository URL to download bootstrap image:
```
==> Executing: "env root_password=root /usr/share/lxc/templates/lxc-fedora --path /build/containers/LXC_NAME --rootfs /build/containers/LXC_NAME/rootfs --name LXC_NAME -R 24 -a x86_64" in /
Checking cache download in /var/cache/lxc/fedora/24-x86_64/rootfs ... 
Downloading x86_64 rootfs for Fedora 24 ...
Non-Fedora host detected. Checking for bootstrap environment ... 
Setting up new Fedora 25 (x86_64) bootstrap environment.
Warning: Failed to get a mirror on try 1.
Trying again ... Warning: Failed to get a mirror on try 2.
Trying again ... Warning: Failed to get a mirror on try 3.
Trying again ... Warning: Failed to get a mirror on try 4.
Error: Failed to retrieve Fedora mirror URL. Please use '-m MIRROR' option.
Error: Fedora Bootstrap setup failed
Error: Failed to download Fedora 24 (x86_64)
Error: Failed to create Fedora container
```

Is it possible that outgoing HTTP requests are blocked for the build container?

**Comment by stgraber** [comment]
I'll go update the list of fedora releases on Jenkins, that should take care of most of that, then I'll take a look at what may be causing the list download problem.

**Comment by stgraber** [comment]
Release list updated, doing a manual run on buildd01 now to see what's going on

**Comment by stgraber** [comment]
++ curl --silent --show-error --fail 'https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-24&arch='
++ sed '/^https:/!d'
++ sed '2,6!d'
+ mirror_urls=
+ '[' 0 -eq 0 ']'
+ '[' -n '' ']'
+ echo 'Warning: Failed to get a mirror on try 1.'

**Comment by stgraber** [comment]
so looks like the problem is the architecture isn't passed somehow

**Comment by stgraber** [comment]
@ganto so the problem is that get_mirrors() assumes that target_arch is defined, but it's not, which causes an invalid URL to be hit.

**Comment by stgraber** [comment]
Working around this issue, I then hit:

Error: Download of squashfs image failed.

**Comment by stgraber** [comment]
That seems to be because you wrote:

     for url in ${mirror:${mirror_urls}}

Instead of:

     for url in ${mirror:-${mirror_urls}}

Fixing that gets me a bit further

**Comment by stgraber** [comment]
Next issue is that:

    if ! curl --silent --show-error --fail --remote-name "${mirror}${image_path}"

Should instead be:

    if ! curl --silent --show-error --fail --remote-name "${url}${image_path}"

**Comment by stgraber** [comment]
That's the failing because image_path is /linux/releases/25/Everything/x86_64/os/images/install.img and url is https://mirror.its.sfu.ca/mirror/fedora/linux/releases/24/Everything/x86_64/os/ which doesn't result in a working path.

**Comment by stgraber** [comment]
@ganto hopefully that's enough for you to come up with a fix :)

**Comment by ganto** [comment]
Hmpf. I apologize, I shouldn't code when being offline... @stgraber Thanks a lot for your investigation.

**Comment by ganto** [comment]
@stgraber Seems with lxc/lxc#1437 the build errors are fixed now. Thanks for merging. However, there are still some little issues in the CI script:
```
 ==> Executing: "chroot /build/containers/LXC_NAME/rootfs sh -c passwd -dl root" in /
passwd: Only one of -l, -u, -d, -S may be specified.
 ==> Executing: "chroot /build/containers/LXC_NAME/rootfs sh -c yum -y remove openssh-server" in /
sh: yum: command not found
```
`yum` was replaced by `dnf` in the recent Fedora releases. Do you want me to send a fix or you do this by yourself?
