### ISSUE TITLE
ArchLinux images on arm64 stuck in grub

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc-ci#150]
https://discuss.linuxcontainers.org/t/lxd-virtual-machines-runing-perfectly-in-raspberry-pi-4/7706/3

**Comment by LaneGeek** [comment]
This happens:-

BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1): Access Denied

So then I disable secure boot and then this happens:-

                             GNU GRUB  version 2.04

   Minimal BASH-like line editing is supported. For the first word, TAB   
   lists possible command completions. Anywhere else TAB lists possible   
   device or file completions.                                            


grub>

**Comment by stgraber** [comment]
Disabled arm64 images as grub is busted on ArchLinux...

I did some poking at it and confirmed that we have a valid grub.cfg and that a manual attempt to boot with linux/initrd/boot works just fine, the issue appears to be that the arm64 build of grub on arch isn't properly handling the menu and boot options in grub.cfg, preventing boot.
