### ISSUE TITLE
openSUSE Tumbleweed VM images on arm64 failed to boot

### ISSUE THREAD

**Issue by LaneGeek** [lxc/lxc-ci#151]
This happens:-

BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1): Access Denied

So then I disable secure boot and then this happens:-

  Booting `openSUSE Tumbleweed'

Loading Linux 5.6.8-1-default ...
error: can't find command `linuxefi'.
Loading initial ramdisk ...
error: can't find command `initrdefi'.

Press any key to continue...

  Failed to boot both default and fallback entries.

Press any key to continue...

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by monstermunchkin** [comment]
@LaneGeek Have you been able to test the updated openSUSE image?

**Comment by LaneGeek** [comment]
> @LaneGeek Have you been able to test the updated openSUSE image?

I tested it just now, and it works!!!!

Thanks 👍

Unfortunately, Arch still does not work...

**Comment by monstermunchkin** [comment]
> I tested it just now, and it works!!!!

OK, great. I'm closing this issue as the Tumbleweed problem has been resolved, and Arch has it's own GitHub issue.
