### ISSUE TITLE
Debian bullseye/sid VMs broken?

### ISSUE THREAD

**Issue by kkremitzki** [lxc/lxc-ci#172]
Hi, it seems the aforementioned VMs are broken. I can e.g. `lxc launch images:debian/buster --vm` and then `lxc shell` or `lxc exec` with it as expected. However if I try the same with `images:debian/bullseye` or `/sid`, I get `Error: Failed to connect to lxd-agent`. From the output of `lxc ls`, I can tell it's at least come up successfully and has an IPv4 and IPv6 address. Per `lxc version`, I have:

```
Client version: 4.2
Server version: 4.2
```

**Comment by stgraber** [comment]
Does it seem to boot correctly when looking at lxc console?

**Comment by kkremitzki** [comment]
Yes, I get e.g.:

```
To detach from the console, press: <ctrl>+a q

distrobuilder-b67f12b8-af3f-4ffb-b479-c7e90ed10ecd login:
```

**Comment by stgraber** [comment]
Ok, that suggests there may have been some kind of kernel change leading to missing required bits for the LXD agent.

**Comment by stgraber** [comment]
@monstermunchkin please investigate

**Comment by monstermunchkin** [comment]
None of the mentioned images seem to be broken. I tried buster (53df0fa229ad), bullseye (9709843ba38c), and sid (e2e8641026ab), and was able to connect to all of them using `lxd shell`.

@kkremitzki Are you using the same images (i.e. same hashes)? If not, could you update your images and see if the problem remains?

**Comment by kkremitzki** [comment]
Yep, those are the same hashes I'm using. I'm seeing this behavior on 3 different machines, 2 of them running Debian 10 with the backports kernel and an Ubuntu 19.10 machine.

**Comment by kkremitzki** [comment]
I think this is IPv6 related because I have been troubleshooting a problem with my network config recently; I justed tested on a fresh DigitalOcean VM and the same bullseye/sid images work. Still, it's strange that my "not sure why it's not quite right" IPv6 setup would work for buster but not other releases.

**Comment by stgraber** [comment]
Yeah, it's a bit strange especially as lxd-agent doesn't use the network and the unit is supposed to start before any networking stuff anyway.

**Comment by stgraber** [comment]
I'm getting the same issue here though.

**Comment by stgraber** [comment]
It's a race condition, everything boots fine but the agent attempts to start before /dev/virtio-ports/org.linuxcontainers.lxd becomes visible.

**Comment by stgraber** [comment]
https://github.com/lxc/distrobuilder/pull/348

**Comment by stgraber** [comment]
The fix has been merged, I'll re-build things so we get testing from those images tonight.
