### ISSUE TITLE
Alpine VM Image (Arm64) Fails To Boot

### ISSUE THREAD

**Issue by LaneGeek** [lxc/lxc-ci#176]
I am very pleased to see a VM image for Alpine Linux 3.12. Unfortunately on the Raspberry Pi (Arm 64), it fails to boot.

It gets very far, but then gets stuck. Here are the last few lines from the console:-

[    1.355424] PCI Interrupt Link [GSI1] enabled at IRQ 36                                                              
[    1.360881] pcieport 0000:00:01.0: PME: Signaling with IRQ 42                                                        
[    1.363813] pcieport 0000:00:01.0: pciehp: Slot #0 AttnBtn+ PwrCtrl+ MRL- AttnInd+ PwrInd+ HotPlug+ Surprise+ Interlock+ NoCompl- LLActRep+                                                                                                  
[    1.374613] pcieport 0000:00:01.1: PME: Signaling with IRQ 43                                                        
[    1.377583] pcieport 0000:00:01.1: pciehp: Slot #0 AttnBtn+ PwrCtrl+ MRL- AttnInd+ PwrInd+ HotPlug+ Surprise+ Interlock+ NoCompl- LLActRep+                                                                                                  
[    1.390202] pcieport 0000:00:01.2: PME: Signaling with IRQ 44                                                        
[    1.393175] pcieport 0000:00:01.2: pciehp: Slot #0 AttnBtn+ PwrCtrl+ MRL- AttnInd+ PwrInd+ HotPlug+ Surprise+ Interlock+ NoCompl- LLActRep+                                                                                                  
[    1.403115] pcieport 0000:00:01.3: PME: Signaling with IRQ 45                                                        
[    1.406084] pcieport 0000:00:01.3: pciehp: Slot #0 AttnBtn+ PwrCtrl+ MRL- AttnInd+ PwrInd+ HotPlug+ Surprise+ Interlock+ NoCompl- LLActRep+                                                                                                  
[    1.417414] pcieport 0000:00:01.4: PME: Signaling with IRQ 46                                                        
[    1.423119] pcieport 0000:00:01.4: pciehp: Slot #0 AttnBtn+ PwrCtrl+ MRL- AttnInd+ PwrInd+ HotPlug+ Surprise+ Interlock+ NoCompl- LLActRep+                                                                                                  
[    1.433544] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled                                                  
[    1.438771] cacheinfo: Unable to detect cache hierarchy for CPU 0                                                    
[    1.441967] rtc-efi rtc-efi: registered as rtc0                                                                      
[    1.445018] registered taskstats version 1                                                                           
[    1.447412] Loading compiled-in X.509 certificates                                                                   
[    1.451811] Loaded X.509 cert 'Build time autogenerated kernel key: bdc7ce04d5acd77fd0a3891f9e7eca91341a188c'        
[    1.456663] Key type ._fscrypt registered                                                                            
[    1.458629] Key type .fscrypt registered                                                                             
[    1.461919] rtc-efi rtc-efi: setting system clock to 2020-07-06T17:28:21 UTC (1594056501)                            
[    1.466356] Freeing unused kernel memory: 768K                                                                       
[    1.508944] Run /init as init process                                                                                
[    1.552344] SCSI subsystem initialized                                                                               
[    1.567662] ACPI: bus type USB registered                                                                            
[    1.569881] usbcore: registered new interface driver usbfs                                                           
[    1.572581] usbcore: registered new interface driver hub                                                             
[    1.575113] usbcore: registered new device driver usb
[    1.582706] usbcore: registered new interface driver usb-storage
[    1.939670] loop: module loaded
[    2.004886] virtio-pci 0000:01:00.0: enabling device (0000 -> 0002)
[    2.019077] virtio-pci 0000:01:00.2: enabling device (0000 -> 0002)
[    2.028805] virtio-pci 0000:01:00.3: enabling device (0000 -> 0002)
[    2.039045] virtio-pci 0000:01:00.4: enabling device (0000 -> 0002)
[    2.049045] virtio-pci 0000:01:00.5: enabling device (0000 -> 0002)
[    2.065785] virtio-pci 0000:03:00.0: enabling device (0000 -> 0002)
[    2.103872] input: QEMU Virtio Keyboard as /devices/pci0000:00/0000:00:01.0/0000:01:00.2/virtio2/input/input0
[    2.112889] input: QEMU Virtio Tablet as /devices/pci0000:00/0000:00:01.0/0000:01:00.3/virtio3/input/input1
[    2.125541] scsi host0: Virtio SCSI HBA
[    2.130480] scsi 0:0:0:1: Direct-Access     QEMU     QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[    2.171622] random: fast init done
[    2.180487] sd 0:0:0:1: Power-on or device reset occurred
[    2.185672] sd 0:0:0:1: [sda] 19531248 512-byte logical blocks: (10.00 GB/9.31 GiB)
[    2.195497] sd 0:0:0:1: [sda] Write Protect is off
[    2.199956] sd 0:0:0:1: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    2.257580]  sda: sda1 sda2
[    2.261807] sd 0:0:0:1: [sda] Attached SCSI disk
[    2.325669] [drm] pci: virtio-gpu-pci detected at 0000:04:00.0
[    2.328211] [drm] virgl 3d acceleration not supported by host
[    2.330792] [drm] EDID support available.
[    2.334358] [TTM] Zone  kernel: Available graphics memory: 228446 KiB
[    2.337151] [TTM] Initializing pool allocator
[    2.339525] [TTM] Initializing DMA pool allocator
[    2.341593] [drm] number of scanouts: 1
[    2.343296] [drm] number of cap sets: 0
[    2.346437] [drm] Initialized virtio_gpu 0.1.0 0 for virtio8 on minor 0
[    2.355174] Console: switching to colour frame buffer device 128x48
[    2.378869] virtio_gpu virtio8: fb0: virtio_gpudrmfb frame buffer device
[    2.715551] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)

**Comment by stgraber** [comment]
@monstermunchkin this one's for you

**Comment by noraj** [comment]
```
$ sudo $HOME/go/bin/distrobuilder build-lxd alpine.yaml 
Error: Error while downloading source: Bad Alpine release:
```

**Comment by LaneGeek** [comment]
Is this fixed now?

**Comment by monstermunchkin** [comment]
@LaneGeek No, unfortunately this is not fixed yet.

**Comment by goost** [comment]
Any infos on what is wrong/where to investigate?

On my x86_64 Ubuntu machine the alpine images, started as a VM, are also failing to boot.
First, boot from HDD fails (`Access Denied`) and then it tries to boot via PXE and HTTP from network which, of course, fails too:
```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)/Scsi(0x0,0x1): Access Denied

>>Start PXE over IPv4.
  PXE-E16: No valid offer received.
BdsDxe: failed to load Boot0003 "UEFI PXEv4 (MAC:00163E2106F5)" from PciRoot(0x0)/Pci(0x1,0x4)/Pci(0x0,0x0)/MAC(00163E2106F5,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)
: Not Found

>>Start PXE over IPv6.
  PXE-E16: No valid offer received.
BdsDxe: failed to load Boot0004 "UEFI PXEv6 (MAC:00163E2106F5)" from PciRoot(0x0)/Pci(0x1,0x4)/Pci(0x0,0x0)/MAC(00163E2106F5,0x1)/IPv6(0000:0000:0000:0000:0000:0000:0000:0000,0
x0,Static,0000:0000:0000:0000:0000:0000:0000:0000,0x40,0000:0000:0000:0000:0000:0000:0000:0000): Not Found

>>Start HTTP Boot over IPv4...
```

**Comment by stgraber** [comment]
@goost set security.secureboot=false as Alpine doesn't provide a signed bootloader

**Comment by goost** [comment]
Great, thanks, that works!

Sorry for not catching that myself. Where should I look in the documentation the next time?

**Comment by stgraber** [comment]
We mentioned it in the Virtual Machines tutorial I believe, though exactly what distros and releases need secureboot varies and we haven't yet found a great way to annotate the images that need it (we also don't want to auto-disable security features based on image metadata).

**Comment by stgraber** [comment]
Just gave it another go now and it's still getting stuck :(
Booting alpine/edge goes slightly further, we're getting `Mounting root: ok.` but still no login prompt or agent...

**Comment by stgraber** [comment]
Is that still an issue?
