### ISSUE TITLE
gentoo image sets system-wide ACCEPT_KEYWORDS

### ISSUE THREAD

**Issue by pajot** [lxc/lxc-ci#187]
The [gentoo.yaml image sets ACCEPT_KEYWORDS.](https://github.com/lxc/lxc-ci/blob/2e90f9deb2502ad74c627efce6ff9fd53e5e7b72/images/gentoo.yaml#L472)

Gentoo has stable and unstable ebuilds in its tree. Unstable ebuilds are generally intended for testing before being declared stable. Setting the entire system unstable can cause problems and is potentially irreversible.

See [https://wiki.gentoo.org/wiki/Knowledge_Base:Accepting_a_keyword_for_all_packages](url)

> Developers or end users might want to use the latest available packages for their entire system, regardless if these packages are already considered production-ready or not. This will result in a system that has more recent software on it, but also receives a much higher update cycle and has a higher risk of system malfunction due to bugs.

There is little reason to set ACCEPT_KEYWORDS for all packages. For those that need it, it is a simple matter of setting an individual keyword for the package in question in `/etc/portage/package.accept_keywords`.

**Comment by stgraber** [comment]
@monstermunchkin
