### ISSUE TITLE
need helps

### ISSUE THREAD

**Issue by hupangpang** [lxc/lxc-ci#19]
i an new of linux, the testbuild-gcc program need file, deps/exercise , but where can i find the exercise file?
can anyone help me with it please!

**Comment by stgraber** [comment]
Yeah, this branch isn't exactly meant to be run locally, it's really meant to be the thing that our Jenkins uses.

**Comment by stgraber** [comment]
the README however does give a hint about where to find the file "from Debian packaging".

https://github.com/lxc/lxc-pkg-ubuntu/blob/dpm-bionic/debian/tests/exercise for example (varies based on what version you want to test against).

**Comment by hupangpang** [comment]
thanks, i am just start learning lxc, it really helps
