### ISSUE TITLE
GPG key data in image yml is undocumented

### ISSUE THREAD

**Issue by blurfurb** [lxc/lxc-ci#206]
It would be good if the key data in the image yml files were more easily auditable, so could you please add some comments/documentation that justifies why the key data is correct? For example,  debian.yml has a list of fingerprints and public key blocks, so it would be nice to know the following about that data:

- why are these the right keys to use? a link to debian documentation that mentions those fingerprints would suffice
- if the key data was extracted by some apt command, what was the command?
- how could one check that this list of keys is up to date with the keys the distro uses now?

If you can offer some guidance about how to answer those questions, I'll volunteer to add this information as documentation, at least for debian.

Thanks

**Comment by stgraber** [comment]
They are all Debian official keys that have been added as they get rotated between releases or architectures.

Easiest to add comments on what they are would be to just import them into GPG and look at their name as those tend to be pretty clear.

**Comment by blurfurb** [comment]
Thanks for the feedback, I'll hopefully have time to look into this and make a pull request soon.

**Comment by stgraber** [comment]
Closing as so far we've found that confirming the fingerprint of each key being added and making sure we have a comment with the fingerprint has been sufficient. From there it's easy to either recheck the keys against a suitable keyring or look them up in one of the many GPG keyservers and then validate them by looking at the web of trust there (distro keys tend to be cross-signed or signed by an offline master key with key contributors of the distro sometimes also signing those keys).
