### ISSUE TITLE
No IP address obtained from downloaded ubuntu trusty image

### ISSUE THREAD

**Issue by LarsFronius** [lxc/lxc-ci#23]
I am assuming this is the right repository to place issues with the images obtained via the `lxc-download` template.

I am running a ubuntu xenial host and run off the lxc 3.0 release from https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/stable.
If I create container via `lxc-create -n foobar -t download -- -d ubuntu -r trusty -a amd64` and start it via `lxc-start`, it doesn't obtain an IP address and generally it looks like a very bare bone linux host (no `/var/log/syslog` file to begin with).
Doing the same and replace `-r trusty` with `-r xenial` and I get a working container.

What's interesting - if I create the ubuntu trusty container via the ubuntu template (from the lxc-templates package in version 3.0), like so: `lxc-create -n foobar -t ubuntu -- -r trusty -a amd64` I get a working container, obtaining IP addresses via DHCP from the host and with a working syslog file.

I am wondering now how the downloaded image is/can be different from the one I built via the ubuntu template.

**Comment by stgraber** [comment]
Can you try adding this to your container's config, see if that unsticks it?
```
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
```
