### ISSUE TITLE
Since 20180502 ubuntu/bionic/amd64 is not getting ip after lxd container creation

### ISSUE THREAD

**Issue by fbourqui** [lxc/lxc-ci#24]
it's due to bad version 2 added in the wrong place in /etc/netplan/10-lxc.yaml:
network:
  ethernets:
    eth0: {dhcp4: true}
version: 2

Last 2 version have this issue:
Ubuntu bionic amd64 (20180502_09:49) 87b5c0fec8ff
Ubuntu bionic amd64 (20180503_07:43) 4d1d191c4128

Previous one was good:
Ubuntu bionic amd64 (20180501_03:49) 856aae255ed4

/etc/netplan/10-lxc.yaml:
network:
  version: 2
  ethernets:
    eth0: {dhcp4: true}

**Comment by stgraber** [comment]
Looking into this now, we change image building method yesterday, so that's likely the source of the problem.

**Comment by stgraber** [comment]
Fixed and triggered a general rebuild.
