### ISSUE TITLE
Add cloud-init to Arch Linux LXD Image

### ISSUE THREAD

**Issue by jelly** [lxc/lxc-ci#242]
Arch Linux has [cloud-init](https://archlinux.org/packages/community/any/cloud-init/) packaged in the repository, so I am wondering if it could be added to the default arch linux image

**Comment by stgraber** [comment]
Not in the main image, but we could add a `cloud` variant as we do the others.

@monstermunchkin

**Comment by jelly** [comment]
Sounds good to me!
