### ISSUE TITLE
Race in image publishing on images.linuxcontainers.org

### ISSUE THREAD

**Issue by iainlane** [lxc/lxc-ci#25]
simplestreams was advertising

```"20180522_07:53": {"items": {"root.tar.xz": {"size": 78471080, "path": "images/ubuntu/artful/armhf/default/20180522_07:53/rootfs.tar.xz", "ftype": "root.tar.xz", "sha256": "89172b09e7fcaf0d321cd8cfeacffe7e8657bde75d2031868f3cd8431ec67915"}```

but

```ubuntu@lxd-armhf13:~$ lxc launch images:ubuntu/artful/armhf
Creating the container
error: Failed container creation:
 - https://images.linuxcontainers.org: Unable to fetch https://images.linuxcontainers.org/images/ubuntu/artful/armhf/default/20180522_07:53/lxd.tar.xz: 404 Not Found
```

was happening. This has just resolved itself, so it looks like a race or maybe a caching/CDN problem.

**Comment by stgraber** [comment]
Hmm, odd. The frontends are meant to rsync the data ahead of the indices to avoid this issue, so I wonder if it's mod_geoip that somehow sent one of your requests to the US servers and then the other to the UK servers? That'd explain it as there's no sync guarantee between the two set of servers.

**Comment by stgraber** [comment]
@iainlane has that been a problem for you recently or is the current syncing logic better and avoiding such races?

**Comment by iainlane** [comment]
@stgraber sorry for not replying before, but (un) luckily it's happening for me right now:

This happened:

```
laney@broadgate:~ $ lxc launch images:debian/10/armhf dns
Creating dns
Error: Failed container creation: Unable to fetch https://images.linuxcontainers.org/images/debian/buster/armhf/default/20190803_05:24/lxd.tar.xz: 404 Not Found
```

Right now when I [browse to the directory](https://uk.images.linuxcontainers.org/images/debian/buster/armhf/default/20190803_05:24/), it is empty. If it's the same thing as I had before it'll probably resolve shortly.

**Comment by stgraber** [comment]
I've reworked our publishing script to do atomic updates, keeping the old data around until the next publishing run, this should avoid this kind of problem, assuming that the frontends run by Canonical IS don't do anything too weird when they rsync.
