### ISSUE TITLE
Please add openSUSE Leap 15 builds

### ISSUE THREAD

**Issue by hwoarang** [lxc/lxc-ci#26]
Hello,

openSUSE Leap 15 has been released, so it would be nice to add a new job to build suitable images. The existing template should work fine. Thank you.

**Comment by stgraber** [comment]
Doesn't work, just tried adding it to Jenkins and the opensuse template refuses leap/15.0 as a release.

**Comment by hwoarang** [comment]
OK I will double check the template and submit a PR if necessary

**Comment by hwoarang** [comment]
@stgraber the repository changed quite a bit since the last time I looked at it for 42.3 Do you know where this opensuse template is nowadays so I can look at it?

**Comment by stgraber** [comment]
https://github.com/lxc/lxc-templates

**Comment by hwoarang** [comment]
Thank you for the quick reply. I have now opened https://github.com/lxc/lxc-templates/pull/9

**Comment by hwoarang** [comment]
Could we try this once more now that the template is in? :) thank you

**Comment by stgraber** [comment]
https://jenkins.linuxcontainers.org/job/lxc-template-opensuse/1672/arch=amd64,release=15.0,restrict=lxc-priv,variant=default/console

Still not working

**Comment by hwoarang** [comment]
The url is not working. Is there a way for you to paste the error? I will try to have a look on my system as well.

**Comment by stgraber** [comment]
I believe the error was related to grabbing the generated rootfs at the end. Our CI passed `leap/15.0` as the release, should be pretty easy to reproduce with that.

**Comment by stgraber** [comment]
From what I remember of the error (now expired as you noticed), it was related to some path not existing, that path contained `leap/15.0` so I suspect something might have been expecting just `15.0` in that path.

**Comment by hwoarang** [comment]
Thank you for the information. I will look into it as soon as possible

**Comment by hwoarang** [comment]
@stgraber I have sent a new PR https://github.com/lxc/lxc-templates/pull/10 which hopefully addresses all your issues. Let me know if you still have problems.

**Comment by stgraber** [comment]
Looks like it's built this time.
