### ISSUE TITLE
lxc-test-checkpoint-restore seems to be skipped on Jenkins

### ISSUE THREAD

**Issue by evverx** [lxc/lxc-ci#267]
I borrowed some shell code from `deps/lxc-exercise`, `bin/build-image-lxc` and `bin/testbuild-gcc` to make it possible to run the tests under ASan/UBsan on GHActions in https://github.com/lxc/lxc/pull/3787. Trying to figure out why `lxc-test-checkpoint-restore` failed (https://github.com/lxc/lxc/issues/3792) I went to the Jenkins dashboard to see whether it passed there and as far as I can tell it passed there in 0s. My guess would be that it was skipped because `criu` wasn't installed.

**Comment by stgraber** [comment]
Yeah, that's normal. Jenkins runs the tests inside of a container, CRIU doesn't support running inside of a container.
