### ISSUE TITLE
Feature request - add OpenWrt arm64 and armhf

### ISSUE THREAD

**Issue by ja-pa** [lxc/lxc-ci#269]
Hi,
would it be possible to add to OpenWrt jenkins job arm64(aarch64) and armhf(armv7) architectures ?
These images could be then used with lxc on arm based routers (see https://github.com/openwrt/packages/blob/master/utils/lxc/Makefile)

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by gmiranda** [comment]
May I ask what's currently blocking this? I had a quick look at your build system and couldn't figure out how the hell it downloads any file from the OpenWrt page :rofl:

**Comment by stgraber** [comment]
Not sure! @monstermunchkin

**Comment by monstermunchkin** [comment]
@gmiranda The reason is that OpenWrt for ARM needs to be built on x86, but we don't support cross builds. You'll need to build the container yourself using `distrobuilder`.

**Comment by stgraber** [comment]
Ah right, that was it, we don't support cross building on our infrastructure and running natively on ARM doesn't work.

**Comment by gmiranda** [comment]
And I guess using OpenWRT's armvirt64/32 rootfs binary package is out ot the question, isn't it?

**Comment by monstermunchkin** [comment]
I just looked into it.

We use https://github.com/mikma/lxd-openwrt as part of our build process. This should build a patches `procd`. However, I just discovered that none of the versions we build seem to need a patch. I'm therefore wondering if we need this repo at all.

Should this not be the case, we could simplify our build process and possibly provide armvirt images as well.

**Comment by monstermunchkin** [comment]
https://github.com/lxc/distrobuilder/pull/542

**Comment by gmiranda** [comment]
> I just looked into it.
> 
> We use https://github.com/mikma/lxd-openwrt as part of our build process. This should build a patches `procd`. However, I just discovered that none of the versions we build seem to need a patch. I'm therefore wondering if we need this repo at all.
> 
> Should this not be the case, we could simplify our build process and possibly provide armvirt images as well.

According to cvmiller/openwrt-lxd (and as far as I can see) there's no need to patch anything on versions 19.07 and upwards. I'll give that a try as soon as possible

**Comment by monstermunchkin** [comment]
> > I just looked into it.
> > We use https://github.com/mikma/lxd-openwrt as part of our build process. This should build a patches `procd`. However, I just discovered that none of the versions we build seem to need a patch. I'm therefore wondering if we need this repo at all.
> > Should this not be the case, we could simplify our build process and possibly provide armvirt images as well.
> 
> According to cvmiller/openwrt-lxd (and as far as I can see) there's no need to patch anything on versions 19.07 and upwards. I'll give that a try as soon as possible

I tested 19.07, 21.02, and snapshot, and all of them worked without having to use the repo.

**Comment by monstermunchkin** [comment]
#387
