### ISSUE TITLE
Please add Fedora 28 builds

### ISSUE THREAD

**Issue by duck-rh** [lxc/lxc-ci#27]
Quack,

It has been released recently and having it at hand would be be very useful.

\\_o<

**Comment by stgraber** [comment]
The lxc-templates script for Fedora fails when attempting to build Fedora 28, until someone fixes that, we can't add the build to Jenkins.

**Comment by cquike** [comment]
Hi, according to this commit Fedora 28 supported has been added to lxc-fedora.in:
https://github.com/lxc/lxc-templates/commit/92fd4dd9ad6cf10d7cc364c17ffa196c08134635#diff-3ad8efc3028672522f47fed48d2b784e

Is that enough to support Fedora 28 builds?
Thank you!

**Comment by stgraber** [comment]
Pretty sure I tried that and it failed, but I can try it again easily enough.

**Comment by stgraber** [comment]
Looks like that worked.

**Comment by duck-rh** [comment]
thanks you folks :-)
