### ISSUE TITLE
Mask systemd-journald-audit.socket in systemd containers

### ISSUE THREAD

**Issue by mkg20001** [lxc/lxc-ci#276]
Currnelty systemd attempts to start systemd-journald-audit.socket due to conditions not matching, but it always fails to start.

It makes sense to mask this unit during distrobuilder build to keep it disabled.

**Comment by stgraber** [comment]
@monstermunchkin can you send a PR to disable that unit on systemd based distros?

**Comment by monstermunchkin** [comment]
Fixed in #278
