### ISSUE TITLE
Add OpenWrt

### ISSUE THREAD

**Issue by oxr463** [lxc/lxc-ci#31]
Could you please add support for OpenWrt?

See also: https://gitlab.com/lramage94/lxc-templates/issues/1

**Comment by stgraber** [comment]
These days all our public images are built through distrobuilder.
The recommended way forward would be to add openwrt to distrobuilder at https://github.com/lxc/distrobuilder once done, I can easily add this to our image building pipeline.

**Comment by oxr463** [comment]
Commit: https://github.com/lxc/distrobuilder/commit/043e58760523b7048ca2dd25a1c9e2ccf0e275ce

**Comment by aparcar** [comment]
Would be cool to add this as an image, however it requires daily rebuilds as currently only snapshots (daily builds of master branch) are supported.

**Comment by stgraber** [comment]
Yeah, that's fine, all our images are built daily anyway.

I'm on vacation for two weeks so have pretty limited time to deal with new images right now, but I'm attending it to my todo so we should have published images in the next few weeks.

**Comment by aparcar** [comment]
Ping?

**Comment by stgraber** [comment]
That was done quite a while back, `images:openwrt` works fine here

**Comment by aparcar** [comment]
Awesome, sorry for bothering!
