### ISSUE TITLE
Debian images missing both ssh / cloud-init

### ISSUE THREAD

**Issue by plaes** [lxc/lxc-ci#32]
Current debian images cannot be easily used in an "automated" way because openssh-server is not installed/enabled and also cloud-init (issue #16) is missing.

**Comment by stgraber** [comment]
lxc-attach or 'lxc exec' will work just fine. We may in time add cloud-init to our images but we're unlikely to do so until all images can have it.

**Comment by plaes** [comment]
Well, I sort of overreacted. Let's close it.
