### ISSUE TITLE
images:debian/jessie has 100% systemd-networkd CPU usage

### ISSUE THREAD

**Issue by julian-klode** [lxc/lxc-ci#33]
Just launch a new jessie container, and you end up with systemd-networkd in it running, utilizing an entire CPU core.

**Comment by stgraber** [comment]
What LXD version are you using? Unless you're running edge, the apparmor profile is likely to prevent you from running any of those units.

**Comment by stgraber** [comment]
jessie: 215 (broken)
stretch: 232 (fine)
sid: 240 (fine)

So this looks like a networkd issue which got fixed upstream and is now fine, if someone can track it down, it would be worth filing a bug against Debian's systemd package to have the fix included.

I'm closing the issue on our end as we don't have any special casing for jessie which would cause this and it instead looks like a systemd bug in jessie which got subsequently fixed.
