### ISSUE TITLE
Add the posibility to access Fedora "legacy" images

### ISSUE THREAD

**Issue by cquike** [lxc/lxc-ci#34]
The Fedora images published at https://images.linuxcontainers.org/ included versions of Fedora 26, 27 that are now gone. I understand that these versions are no longer supported by Fedora  and therefore it makes sense not to offer them anymore. Unfortunately this has broken our workflow, where we use those images to test our software in different platforms used by the customers (including some which are no longer supported...).

 It would be very useful if those "legacy" images are still available, maybe via a different image server like legacy.images.linuxcontainers.org and with the relevant disclaimer, of course.

**Comment by cquike** [comment]
The same could potentially apply to other legacy images from other distributions, of course.

**Comment by stgraber** [comment]
It seems unlikely that we would take on something like this ourselves. We're already dealing with a dataset of several hundreds GBs of images and that's just for the actively maintained ones. Adding on legacy images may run some of our GeoIP mirrors out of space which would be a problem.

It would also need us to closely monitor the EOL of every release of every distribution which isn't something I'm that interested in doing personally :)

There's however nothing wrong with someone else doing this themselves and if you're using LXD, you could actually very easily run an internal image server which copies those images you care about daily from our image server. So long as new images are available, you're copying them, once they're no longer available, the copy will fail but you'll be left with the latest version of that image. Your test systems can then always use that system as their image server, saving you bandwidth and giving you more control on the images you're using.
