### ISSUE TITLE
FR: aarch64 gentoo image

### ISSUE THREAD

**Issue by lmchale** [lxc/lxc-ci#341]
Feature Request:
Please add support to build aarch64 gentoo images that would be useful in ampere (neoverse-n1) cloud instances.  I would build myself, but I'm unsure how to replicate the build process.

Similarly, it would be a value add to also include gentoo systemd images, if possible.  It seems like systemd lxd images require some tweaks to get working?  My attempts at getting a gentoo stage3 aarch64 tarball in a happy state are so far unsuccessful.

Thanks!

**Comment by stgraber** [comment]
@monstermunchkin do you know why we have everything except for arm64 on gentoo?

**Comment by monstermunchkin** [comment]
@stgraber I don't recall, but since there is a stage3 tarball for arm64 we should be able to add it.

**Comment by monstermunchkin** [comment]
Closed with #344 and #346
