### ISSUE TITLE
Continue provinding Fedora i386 images 

### ISSUE THREAD

**Issue by cquike** [lxc/lxc-ci#35]
Fedora i386 have been offered in the past and continue to be useful for testing purposes. Since i386 is still offered and supported by Fedora, could you please add them to images.linuxcontainers.org again?

**Comment by stgraber** [comment]
We are building images for all architectures that are available at the time through https://kojipkgs.fedoraproject.org/packages/Fedora-Container-Base/

This currently does not include 32bit Intel images, therefore we cannot build and publish such images.

I'd recommend you reach out to the Fedora project and get them to publish that Intel 32bit artifact, once that's present, we can trivially add the image.
