### ISSUE TITLE
Broken networking not being automatically detected

### ISSUE THREAD

**Issue by Pascal666** [lxc/lxc-ci#350]
Many of the images at https://jenkins.linuxcontainers.org/view/Images/job/image-centos/1310/ show good, even though they do not actually work - see #348

**Comment by stgraber** [comment]
The network test works correctly, it did find the breakage that happened over the weekend.

There is a separate issue where NetworkManager based images tend to fall on some specific older kernels like the one found in RHEL/CentOS but that's not a bug with the image or with LXD, it's an issue with the kernel in question missing logic for proper network device ownership.
