### ISSUE TITLE
Debian images (and others?) lack extended attributes

### ISSUE THREAD

**Issue by fergus-dall** [lxc/lxc-ci#381]
You can verify this by doing
```bash
curl https://us.images.linuxcontainers.org/images/debian/bullseye/amd64/default/20210827_05:24/rootfs.squashfs > rootfs.squashfs
mkdir rootfs
sudo mount rootfs.squashfs rootfs
getfattr -d -m - rootfs/bin/ping
```
You should get an output like
```
# file: rootfs/bin/ping
security.capability=0sAQAAAgAgAAAAAAAAAAAAAAAAAAA=
```
but instead get nothing.

This seems to have started sometime between late May and mid July. We have a build process which takes linuxcontainers debian images and customizes them, and we have good/bad images on those dates. Unfortunately I can't be more specific because we don't run builds very often.

I have tried running distrobuilder versions 1.2, 1.3, and ToT (lxc/distrobuilder@ede7b0cb32a2368ea6e82da2b14c63781feb003e) by hand on the `debian.yaml` file in this repo and they all work correctly: the rootfs from `build-dir` has the right xattrs, and `pack-lxd` generates squashfs images with xattrs included.

This leads me to think something about your build environment is buggy, possibly your version of squashfs-tools (I did my testing with version `1:4.3-6ubuntu0.18.04.2`)

Downstream bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1243699

**Comment by fergus-dall** [comment]
That seems to have done the trick, thanks!

**Comment by fergus-dall** [comment]
Actually, I think this is still broken on arm64 builds, assuming upstream debian isn't doing anything strange there

**Comment by stgraber** [comment]
Oh, you're right, the tmpfs logic only applies to x86_64 on our side, not aarch64 so for that we need the distobuilder fix which we've only merged about an hour ago. Let me kick a new Debian build now as that should fix it for good.

**Comment by stgraber** [comment]
@fergus-dall fixed!

```
stgraber@dakara:~/Downloads$ sudo mount -o loop rootfs.squashfs test/
Please touch the device.
stgraber@dakara:~/Downloads$ getfattr -d -m - test/bin/ping
# file: test/bin/ping
security.capability=0sAQAAAgAgAAAAAAAAAAAAAAAAAAA=
stgraber@dakara:~/Downloads$ file test/bin/ping
test/bin/ping: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=af4a96ebb344ec6896972e6621d7c0ec449b216e, for GNU/Linux 3.7.0, stripped
```
