### ISSUE TITLE
remove sudo from alpine image

### ISSUE THREAD

**Issue by melato** [lxc/lxc-ci#434]
I noticed that the sudo package was added to images/alpine.yaml on Tue Aug 10 07:32:24 2021 +0200.
Why was it added?  I do not see an issue that justifies it.  It seems unnecessary and undesirable for an image that has very few packages.

Here are some reasons to remove sudo:
- alpinelinux maintainers don't like sudo and plan to move it from the main to the community repositories  in version 3.16:
https://alpinelinux.org/posts/Alpine-3.15.0-released.html
https://gitlab.alpinelinux.org/alpine/tsc/-/issues/1
They prefer doas instead of sudo.

- I wanted to test an alpine container without sudo, but I noticed that sudo was already installed in the image.

- It is easy to add sudo anytime, as I was doing before it was added in the image, so why include it by default?

**Comment by stgraber** [comment]
It's basically about consistency with all our other images as part of the minimal feature set we want to provide in them.
In this case, I think it'd be reasonable to tweak the YAML to switch over to doas starting with 3.15.

@monstermunchkin

**Comment by melato** [comment]
The workaround is to create my own alpine image from scratch, using distrobuilder, which I am very pleased to have learned how to use (prompted by this issue).

The value of alpine for me is that its own "minimal feature set" is almost empty, so I can use it to make my own "LXD container distribution" by adding only the packages I want.  I may want to experiment with a container that has neither "sudo" nor "doas".
