### ISSUE TITLE
Adding Arch Linux

### ISSUE THREAD

**Issue by ChlorideCull** [lxc/lxc-ci#5]
What work would need to be done to enable Arch Linux builds? I see, for example, the following:

- Template script requires the arch-install-scripts and pacman.
- Template script does some funky stuff with systemd service files, which isn't needed now, in my experience.
- Template script doesn't mask some services that shouldn't run in a container, like systemd-udevd.
- systemd has some [issues with AppArmor and LXC](https://github.com/lxc/lxc/issues/820), which breaks some vital services. A blocker for running, but no clue if it still can be built.

**Comment by stgraber** [comment]
Ok, so the template issues should be fixed with a pull request again lxc/lxc.
The image builder typically runs on Ubuntu and basically just calls lxc-create -t DISTRO -n LXC_NAME, then compresses the result.

As pacman doesn't appear to be packaged for Ubuntu, you'll need to get archlinux to work properly inside LXC, at least well enough for the build-image script to use an arch image as its base image.
Then archlinux support must be added to the lxc_ci python module (look at what was done for opensuse), after which I should be able to bootstrap things if you provide me with a working arch amd64 tarball I can use as a first base container.

**Comment by ChlorideCull** [comment]
I've not had too much time to work on this, but I got pacman (kinda) packaged for Ubuntu [here](https://github.com/ChlorideCull/pacman-minus-arch). Amusingly, it was just clobbered by an apt-get upgrade, because the actual game is in the repositories, haha.

**Comment by stgraber** [comment]
Ah, nice, that's gonna be much nicer than having to get lxc-ci to work on archlinux :)

**Comment by mcorb** [comment]
It's possible to do an unprivileged bootstrap using the [Arch LiveCD squashfs image](https://wiki.archlinux.org/index.php/Install_from_existing_Linux#Method_B:_Using_the_LiveCD_image):

1) Convert the squashfs to a runnable lxc image:
```
curl -O 'http://mirror.23media.de/archlinux/iso/2016.09.03/arch/x86_64/airootfs.sfs'
unsquashfs -d rootfs airootfs.sfs
patch rootfs/bin/pacstrap < pacstrap-virtual.patch
tar cf arch-installer.tar metadata.yaml rootfs
lxc image import arch-installer.tar
```

2) Bootstrap a clean rootfs:
```
dhclient eth0
mkdir /mnt/rootfs
pacstrap -v /mnt/rootfs
cd /mnt/rootfs
tar -cf ../rootfs.tar .
```

3) Pull and import the generated rootfs as the final Arch Linux image

The pacstrap command needs patches to support unprivileged operation. I'd suggest that this is the path of least resistance, given the lack of sustained effort to support pacman outside of Arch Linux. I can share the patch too - let me know if you have cycles to integrate this into the Jenkins ci build flow.
 
The arch template in lxc looks really dated and I've avoided it completely. Seems easier to start from scratch if going with the above, then refine it to support necessary systemd fixes as time allows.

**Comment by theblazehen** [comment]
@mcorb I'd be interested in that patch. Might do some work on getting it to work with jenkins.

**Comment by lulcat** [comment]
theblazehen, if you use archlinux generally, then just open pacstrap and start patching. It is a bit long, but fairly easy to get around. I have been away for a 3months in a different country and will be going back soon, else I would happily patch it for you guys, if unprivileged ops are entirely possible.

**Comment by lulcat** [comment]
Sigh. has anyone received that patch? I am soon moving again across countries so I have ample time for patching. Should I settle in and all that in a few months, I can find the time.

**Comment by stgraber** [comment]
archlinux has now been added to the image server.
