### ISSUE TITLE
A number of images don't get the IPv4 with lxd 3.03

### ISSUE THREAD

**Issue by cquike** [lxc/lxc-ci#517]
I have tried a few images lately that seem not to get their IPv4 address when starting up in our production LXD 3.0.3 installation (with host Ubuntu 18.04). The images I have tried are:
debian/11
debian/12
fedora/34
fedora/35

The images were working fine in LXD 3.0.3 at least late Jan 2022 when we grab them last time from the images: server.

If a try those images with LXD 4.0.7 (in a testing Debian 11 host) then they get their IPv4 properly.

I have tried additionally images for debian (9,10) and they seem to work fine, as well as all ubuntu (18.04, 20.04, 22.04) and centos (7, 8-Stream). In both hosts (LXD 3.0.3 and 4.0.7).

**Comment by cquike** [comment]
For completion: It seems that a IPV6 address is actually there, but not IPv4. This are the logs of systemd-netword in a Debian/11 container:
```
root@fancy-wombat:~# systemctl  status systemd-networkd
● systemd-networkd.service - Network Service
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-05-12 08:32:36 UTC; 5min ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 75 (systemd-network)
     Status: "Processing requests..."
        CPU: 66ms
     CGroup: /system.slice/systemd-networkd.service
             └─75 /lib/systemd/systemd-networkd

May 12 08:32:35 fancy-wombat systemd[1]: Starting Network Service...
May 12 08:32:36 fancy-wombat systemd-networkd[75]: Failed to increase receive buffer size for general netlink socket, ignoring: Operation not permitted
May 12 08:32:36 fancy-wombat systemd-networkd[75]: Failed to increase buffer size for device monitor, ignoring: Operation not permitted
May 12 08:32:36 fancy-wombat systemd-networkd[75]: eth0: Gained IPv6LL
May 12 08:32:36 fancy-wombat systemd-networkd[75]: Enumeration completed
May 12 08:32:36 fancy-wombat systemd[1]: Started Network Service.

```

As a comparison, in a LXC 4.0.7 host there is one additional line:
`May 12 08:34:54 super-stag systemd-networkd[74]: eth0: DHCPv4 address 10.205.114.101/24 via 10.205.114.1
`

**Comment by cquike** [comment]
There is also a different in the output of networkctl. In the LXC 3.0.3 host:
```
# networkctl
IDX LINK TYPE     OPERATIONAL SETUP
  1 lo   loopback carrier     pending
 34 eth0 ether    routable    pending
```
Whereas in the LXC 4.0.7 host:
```
# networkctl
IDX LINK TYPE     OPERATIONAL SETUP
  1 lo   loopback carrier     unmanaged
128 eth0 ether    routable    configured

```

**Comment by cquike** [comment]
If I manually undo the changes of 6e7038c066bc19e357692ea70f9bab8e38008c10 in the container and reboot then I confirm that IPv4 in Debian/11 are assigned. So it looks as of systemd-networkd running in the container doesn't work with LXC 3.0.3.

**Comment by stgraber** [comment]
@monstermunchkin can you take a look?

**Comment by monstermunchkin** [comment]
@cquike you can "fix" the issue by setting

```
lxc config set <container> raw.lxc "lxc.mount.auto=sys"
```

**Comment by cquike** [comment]
Thank you very much for the advice.
First I thought that it might not work because we create our images in an automatic fashion (with packer), and your suggestion would be applied after the image was created. But by then the image creation has already failed.
Then I realized that I can apply that trick to the default profile with this:
`lxc profile set default raw.lxc "lxc.mount.auto=sys"`
And then all the containers created (including during image creation) have to fix applied. Now everything works fine :)
Thank you!

**Comment by stgraber** [comment]
Closing as I don't believe there's anything we can directly do in the images to make them behave better here and LXD 3.0 is in security-only maintenance at this point so we're unlikely to be releasing a change to its behavior.
