### ISSUE TITLE
Add Arch s390x support to AlmaLinux 9

### ISSUE THREAD

**Issue by srbala** [lxc/lxc-ci#542]
AlmaLinux has s390x support in AlmaLinux 9. It would be great to enable that arch in images.

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by srbala** [comment]
@monstermunchkin @stgraber Thank you for the PR. Noticed build failures for `s390x`, https://jenkins.linuxcontainers.org/job/image-almalinux/ any suggestion to resolve it

**Comment by stgraber** [comment]
It can't be resolved. We'll be removing the s390x architecture for Alma.

The error basically says that you need at least a z14 mainframe to run Alma, the one we have is a z13.
