### ISSUE TITLE
Missing etc/network/interfaces files in todays download-template-release for debian 11 amd64 (August 1st 22)

### ISSUE THREAD

**Issue by ludwig-gramberg** [lxc/lxc-ci#584]
Today I can't create any containers with network access when using the debian 11 amd64 download template: 

`lxc-create -f /etc/lxc/mytest.conf --name mytest --template download -- --release bullseye --arch amd64 --dist debian`

In rootfs the folder `/etc/network` is missing. No `interfaces` file is created and the container does not have access to the network/internet. On another machine with an older template-cache the template does contain the necessary files and containers do behave as expected.

What has changed? Was this an oversight or do templates have to be used differently?

`/usr/share/lxc/templates/lxc-download -l` shows that the template was just changed today:

```
debian	bullseye	amd64	default	20220801_05:24
```

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by stgraber** [comment]
Last change was 3 days ago but shouldn't have touched that.
https://github.com/lxc/lxc-ci/commits/master/images/debian.yaml

**Comment by ludwig-gramberg** [comment]
maybe the date is misleading and I'm not involved enough to know what happened but the download-template for debian bullseye/amd64/default specifically the rootsfs.tar.xz as listed here: https://uk.lxd.images.canonical.com/  is missing the `/etc/network`-part.

**Comment by tomponline** [comment]
Is this because its switched over to using systemd-networkd?

**Comment by tomponline** [comment]
Confirmed that is why, just launched a fresh container using `images:debian/11` and it got IPv4 and IPv6 configured correctly using systemd-networkd:

```
root@c2:~# cat /etc/systemd/network/eth0.network 
[Match]
Name=eth0
[Network]
DHCP=true
[DHCPv4]
UseDomains=true
root@c2:~# networkctl 
IDX LINK TYPE     OPERATIONAL SETUP
  1 lo   loopback carrier     unmanaged
 11 eth0 ether    routable    configured

2 links listed.
```

**Comment by ludwig-gramberg** [comment]
Hi @tomponline so if I want to setup a container with static ip, instead of preparing settings in /etc/network/interfaces I have to do so in /etc/systemd/network/eth0.network ? Is that correct?

**Comment by tomponline** [comment]
If you're connecting your instance to a LXD managed network (such as lxdbr0) you don't need to modify the container's network settings at all, instead you can specify a static DHCP lease using LXD device config, e.g.

```
lxc config device override c1 eth0 ipv4.address=n.n.n.n
```

If you're using an unmanaged network then, yes, you will need to modify that file.

**Comment by ludwig-gramberg** [comment]
I'm using lxc without lxd. Thanks for the tipp! Gonna try that right now :-)

**Comment by ludwig-gramberg** [comment]
Works like a charm.
Thank you!
