### ISSUE TITLE
Ubuntu Desktop image have screen lock enabled

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxc-ci#585]
If you create a VM with `lxc launch images:ubuntu/jammy/desktop --vm` and wait a bit for the screen lock to activate, you won't be able to unlock the graphical session because the `ubuntu` user has no password:

```
# getent shadow ubuntu
ubuntu:!:19205:0:99999:7:::
```

Ideally, screen locking should be disabled.

**Comment by stgraber** [comment]
@monstermunchkin
