### ISSUE TITLE
Re-enable Alpine 3.16

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc-ci#591]
https://github.com/lxc/lxc-ci/commit/a783ed8492467055a36b0f37f6477a10dde44aa6 temporarily disabled Alpine 3.16.

We've had reports that this is working again now: 
https://discuss.linuxcontainers.org/t/images-alpine-3-16-have-disappeared/14883/3?u=tomp

So we should try re-enabling it and see if it works again.

**Comment by melato** [comment]
Incidentally, the uwaterloo.ca mirror used by alpine.yaml was out of date for a few days, but it is now up-to-date.

The first few lines of the distrobuilder output when I build alpine.yaml, are:
```
INFO[2022-08-20T09:23:06Z] Downloading source                           
INFO[2022-08-20T09:23:07Z] Unpacking image                               file=/tmp/distrobuilder/alpinelinux-3.16-x86_64/alpine-minirootfs-3.16.0-x86_64.tar.gz
INFO[2022-08-20T09:23:07Z] Managing repositories                        
INFO[2022-08-20T09:23:07Z] Running hooks                                 trigger=post-unpack
INFO[2022-08-20T09:23:07Z] Managing packages                            
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.2-48-g6b7fcd1ef7 [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
```
So, distrobuilder downloads alpine-minirootfs-3.16.0-x86_64.tar.gz , presumably from the uwaterloo mirror, but then updates packages using dl-cdn.alpinelinux.org.  If the minoroot mirror is out-of-date with alpinelinux.org, then the miniroot may point to packages that have changed?

Note that distrobuilder downloads miniroot 3.16.0, even though 3.16.2 is also available.

**Comment by tomponline** [comment]
Yes that seems problematic. We do expect the resulting image to be configured to use the default mirror, but using different mirrors during image creation seems like asking for trouble. @monstermunchkin what do you think?

**Comment by monstermunchkin** [comment]
We could fix this by supporting pongo in `actions`. This would allow us to do something like this:

```yaml
actions:
- trigger: post-unpack
  pongo: true
  action: |-
    #!/bin/sh
    echo {{ source.url }}/{{ image.release }}/main > /etc/apk/repositories
    echo {{ source.url }}/{{ image.release }}/community >> /etc/apk/repositories
```

**Comment by stgraber** [comment]
I think that'd make sense, we support pongo almost everywhere else, right?

**Comment by monstermunchkin** [comment]
> I think that'd make sense, we support pongo almost everywhere else, right?

We support it in `content` in `files`, and in `targets`. I believe that's it.

**Comment by monstermunchkin** [comment]
> Note that distrobuilder downloads miniroot 3.16.0, even though 3.16.2 is also available.

@melato see https://github.com/lxc/distrobuilder/pull/661
