### ISSUE TITLE
Add Alpine Linux

### ISSUE THREAD

**Issue by jirutka** [lxc/lxc-ci#6]
I already requested it in #4, but the old Alpine build template was not suitable for using with download template.

> @stgraber: Not until someone converts the alpine linux template to something that can be used with the download template.

I rewrote the template and it was already merged (https://github.com/lxc/lxc/pull/751), so I guess that now it can be added to CI. :smile_cat:

**Comment by jirutka** [comment]
ping @stgraber

**Comment by stgraber** [comment]
It has been added a few days ago already. You need LXC 2.0 for it to show up though.

```
alpine	3.0	amd64	default	20160321_17:50
alpine	3.0	i386	default	20160321_17:50
alpine	3.1	amd64	default	20160321_17:50
alpine	3.1	i386	default	20160321_17:50
alpine	3.2	amd64	default	20160321_17:50
alpine	3.2	i386	default	20160321_17:50
alpine	3.3	amd64	default	20160321_17:50
alpine	3.3	i386	default	20160321_17:50
alpine	edge	amd64	default	20160321_17:50
alpine	edge	i386	default	20160321_17:50
```
