### ISSUE TITLE
openEuler builds not stable

### ISSUE THREAD

**Issue by pkking** [lxc/lxc-ci#656]
Hi, team
We are happy to see the openEuler supported in lxc-ci :)
Seems the builds are still in abnormal status, mostly because `repo.openeuler.org` is not global fastly accessable.
Since we are still expanding the edge networking and CDNs, for now maybe you can try some of our others [mirrors](https://www.openeuler.org/en/mirror/list/) and if the mirrors works well, i will make a PR :)

**Comment by stgraber** [comment]
@monstermunchkin can you try with https://ftp.belnet.be/mirror/openeuler/ ?

**Comment by monstermunchkin** [comment]
@stgraber I tried all of the mirrors yesterday. The one you mentioned always caused an EOF error at the end of the download, but I'll try again. Maybe it was just having a bad day.

**Comment by monstermunchkin** [comment]
@stgraber I was wrong. The mirror you mentioned for some odd reason doesn't contain any ISO images.

**Comment by pkking** [comment]
If the runner boxes located in EU, maybe try https://fr-repo.openeuler.org/

**Comment by stgraber** [comment]
They're in Canada and in the US, but you don't seem to have much in the way of mirrors on this side of the planet, so Europe is closest.

**Comment by pkking** [comment]
Any news from this issue?
Maybe build it through a github action?

**Comment by monstermunchkin** [comment]
> Any news from this issue? 

https://ru-repo.openeuler.org/ seems to be reliable.

**Comment by pkking** [comment]
Thanks, i will make a PR to using this repo :)

**Comment by pkking** [comment]
> > Any news from this issue?
> 
> https://ru-repo.openeuler.org/ seems to be reliable.

Seems no luck for `https://ru-repo.openeuler.org/` 
```
+ distrobuilder --cache-dir /root/build/cache/ --timeout 7200 build-dir image.yaml rootfs -o image.serial=20221201_19:04 -o image.architecture=aarch64 -o image.release=22.03 -o image.variant=default
time="2022-12-01T19:04:09Z" level=info msg="Downloading source"
time="2022-12-01T19:04:20Z" level=info msg="Removing cache directory"
Error: Error while downloading source: Failed to get latest release by 22.03: Failed to read url: Get "https://ru-repo.openeuler.org/": net/http: TLS handshake timeout
```
