### ISSUE TITLE
images: add support for Tails

### ISSUE THREAD

**Issue by ajaykarpur** [lxc/lxc-ci#677]
Hi! Just wanted to request adding [Tails](https://tails.boum.org/install/index.en.html) to the list of supported images.

**Comment by stgraber** [comment]
This usually has to start with adding support in https://github.com/lxc/distrobuilder.
Unless it's a clean derivative of another distro and can reuse an existing one.

**Comment by ajaykarpur** [comment]
Got it, thanks! Opened an issue on the `distrobuilder` repo: https://github.com/lxc/distrobuilder/issues/684
