### ISSUE TITLE
Different path conventions for sudo rules

### ISSUE THREAD

**Issue by antifob** [lxc/lxc-ci#678]
Hi,

While acknowledging that it might be a breaking change, would you consider normalizing the path of sudo rules added for the images? Currently, two (2) path formats are used: `/etc/sudoers.d/${USERNAME}`, where `${USERNAME}` is distro-based and `/etc/sudoers.d/90-lxd` (for Ubuntu images).

https://github.com/lxc/lxc-ci/blob/1218136fd353d419630d6928223b41ec0ef1794b/images/opensuse.yaml#L339-L341
https://github.com/lxc/lxc-ci/blob/087d12ba482beec2714cc67a3553f8e0e401961c/images/archlinux.yaml#L682-L684
https://github.com/lxc/lxc-ci/blob/087d12ba482beec2714cc67a3553f8e0e401961c/images/ubuntu.yaml#L465-L470

Thanks for your great work :)

edit: line ranges

**Comment by monstermunchkin** [comment]
Hi,

you're right, this should be consistent. I'll send a fix.
