### ISSUE TITLE
Please add ubuntu-core/18 images to https://us.images.linuxcontainers.org/

### ISSUE THREAD

**Issue by tsteven4** [lxc/lxc-ci#68]
Please add the ubuntu-core/18 images analogous to:

> ubuntu-core/16 (3 more)              | 7a17983ba54d | yes    | Ubuntu-Core 16 amd64 (20190825_07:47)        | x86_64  | 245.93MB | Aug 25, 2019 at 12:00am (UTC) |
+--------------------------------------+--------------+--------+----------------------------------------------+---------+----------+-------------------------------+
| ubuntu-core/16/i386 (1 more)         | 4159a7c6fcfe | yes    | Ubuntu-Core 16 i386 (20190825_07:47)         | i686    | 239.77MB | Aug 25, 2019 at 12:00am (UTC) |

Thanks

**Comment by stgraber** [comment]
Yeah, we've been trying to get it to behave for months now but snapd in that image still has issues.

**Comment by stgraber** [comment]
So we instead went the other way around and remove all Ubuntu Core images.

The workaround we were using to make those work was just too unstable and hard to maintain.

If you'd like those images to be available again, I'd recommend filing a bug on Launchpad (snap-core20 project as a start) asking for proper official support for running those images in containers.

This would likely require some work around model and kernel/bootloader bits as those aren't relevant in containers yet we still want the ability to revert on upgrade failures.
