### ISSUE TITLE
Fedora EOL images cannot acces Fedora repositories

### ISSUE THREAD

**Issue by cquike** [lxc/lxc-ci#704]
We have a need to run Fedora images that already reached EOL. As suggested in #34, we are storing our images in a local server.
However, for the latest Fedora images the dnf repositories configuration has been changed and points to a mirror in Canada. That mirror happens to leave only empty repos for EOL versions and hence the images cannot be used to install any software from the Fedora repos.
If instead the metalink is used then EOL versions (like Fedora 35) still continue to access a valid repository.
I would ask to reconsider using the metalink again so that the images can be used after its EOL.

**Comment by stgraber** [comment]
@monstermunchkin can we make it so we only use the provided mirror in Canada during the image build?
I'd have expected the resulting image to just hit the normal repos.
