### ISSUE TITLE
Amazon Linux 2023 images (for cgroup v2 hosts)

### ISSUE THREAD

**Issue by kdrag0n** [lxc/lxc-ci#717]
Amazon Linux 2 images can't run on systems that use cgroup v2 because AL2's systemd is too old:

```
Error: The image used by this instance requires a CGroupV1 host system
Try `lxc info --show-log local:amazon3` for more info
```

Amazon Linux 2023 is now GA and it includes systemd 252, which is fairly recent. It would be great to have official LXD images for it so we can run Amazon Linux without disabling cgroup v2.

**Comment by kdrag0n** [comment]
`amazonlinux/current` still appears to be Amazon Linux 2, unfortunately.

```
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization lxc.
Detected architecture arm64.

Welcome to Amazon Linux 2!

Initializing machine ID from random generator.
Cannot determine cgroup we are running in: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```

**Comment by stgraber** [comment]
amazonlinux.com and their CDN all still get you Amazon Linux 2.

Where is one supposed to be downloading the new version from?

We rely on: https://cdn.amazonlinux.com/os-images/latest/

**Comment by stgraber** [comment]
I'm not seeing any official download link for this thing, just links to the AWS console to spawn the AMI in their cloud.

**Comment by kdrag0n** [comment]
I'm not sure — haven't been able to find rootfs tarballs either. They do, however, publish the Dockerfile used to build the official Docker images: https://github.com/amazonlinux/container-images/blob/al2023-arm64/Dockerfile

```Dockerfile
RUN ROOTFS=$(curl -sfOJL -w "al2023-container-2023.0.20230322.0-arm64.tar.xz" "https://amazon-linux-docker-sources.s3.amazonaws.com/al2023/2023.0.20230322.0/al2023-container-2023.0.20230322.0-arm64.tar.xz") \
  && echo '7680e34bfabab88e51cfa7c22a704b153fbb0cea807f3d123011d0c02a508b7b  al2023-container-2023.0.20230322.0-arm64.tar.xz' >> /tmp/al2023-container-2023.0.20230322.0-arm64.tar.xz.sha256 \
  && cat /tmp/al2023-container-2023.0.20230322.0-arm64.tar.xz.sha256 \
  && sha256sum -c /tmp/al2023-container-2023.0.20230322.0-arm64.tar.xz.sha256 \
  && mkdir /rootfs \
  && tar -C /rootfs --extract --file "${ROOTFS}"
```

Unfortunately the link to the rootfs changes for every update. I noticed that some lxc-ci distros use `downloader: docker-http` though. Could we do the same thing for Amazon Linux (`amazonlinux:2023` on Docker Hub, or [ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/amazon_linux_container_image.html)) and install packages on top of it?

**Comment by kdrag0n** [comment]
Actually, the public ECR registry doesn't require authentication, so it can be downloaded from `public.ecr.aws/amazonlinux/amazonlinux:2023` as a Docker image.

**Comment by dejlek** [comment]
Any update on this? - If we could do what @kdrag0n suggests that would be great...

**Comment by dejlek** [comment]
@monstermunchkin , can we at least have Amazon Linux 2 images work with CGroupsV2?

**Comment by stgraber** [comment]
CentOS 7 derivatives cannot be made to work with cgroup2, however you can change your system to run cgroup1 instead.

**Comment by dejlek** [comment]
Then I guess all I can do is wait for Amazon Linux 2023 image to be released...

**Comment by stgraber** [comment]
So looks like Amazon did finally publish Amazon Linux 2023 and our images automatically updated to it.

```
[root@a2 ~]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

**Comment by kdrag0n** [comment]
@stgraber Amazon Linux 2 is the old version. 2023 is different:

```
bash-5.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```

**Comment by stgraber** [comment]
Ah, fun... So even their website still sends you to the old stuff.

**Comment by stgraber** [comment]
https://github.com/amazonlinux/amazon-linux-2023/issues/102

That's the issue tracking for them to provide self-hosted images, so far no useful activity.

There are know workarounds like exporting an existing VM or using the Docker image and adding stuff back to get something close to a regular image.

But speaking for our own images, we want something which the distro will support. As it stands Amazon Linux 2023 appears to only be supported as AWS instances from their own images.

Closing this issue as there's nothing actionable until Amazon releases public artifacts for self-hosted use of their distro.

**Comment by kdrag0n** [comment]
Amazon has KVM images now: https://github.com/amazonlinux/amazon-linux-2023/issues/102#issuecomment-1815372559

**Comment by kdrag0n** [comment]
Thanks for the quick addition!

**Comment by stgraber** [comment]
Still needs a bunch of tweaking as the al2023 images are way too empty, they don't come with a functional network config so end up failing our tests.

**Comment by stgraber** [comment]
Should be fixed now, had to add udev to make things behave.

**Comment by kdrag0n** [comment]
Just noticed that arm64 is missing. What's the rationable behind 3ee0725?

**Comment by stgraber** [comment]
Amazon Linux requires a very recent version of arm64 to run which none of our build hardware supports.

This also means that most users wouldn't be able to run those containers for similar reasons.

**Comment by dimitry-unified-streaming** [comment]
> Amazon Linux requires a very recent version of arm64 to run which none of our build hardware supports.
> 
> This also means that most users wouldn't be able to run those containers for similar reasons.

Sorry for pinging on a rather old ticket, but is this still the case in 2025? It looks like Amazon is pretty eager to get everybody onto their Graviton arm64 instances. :)

**Comment by stgraber** [comment]
Yes, Amazon didn't relax the architecture baseline, so the only place such containers could run would be on Graviton or maybe inside a VM on a recent Mac.
