### ISSUE TITLE
Debian Buster Image gone

### ISSUE THREAD

**Issue by dittertp** [lxc/lxc-ci#725]
Hi all,
I was shocked to discover today that the debian buster image has been removed (https://github.com/lxc/lxc-ci/commit/d4f061884c66e7e64218e6fc227f1f53f111d558)

according to the commit message, because the EOL of Debian Buster has been reached, but this is not correct! (see https://wiki.debian.org/LTS). The planned EOL date is June 30th, 2024. 

This is a huge problem for us right now. Is there any way to reverse this change?

Thank you very much!

**Comment by monstermunchkin** [comment]
I got the information from https://wiki.debian.org/DebianReleases which says it's EOL. However, we can revert the commits which remove Debian Buster.

**Comment by tomponline** [comment]
It appears to still be in a reduced LTS support.

**Comment by dittertp** [comment]
Wow! That was fast. Thank you very much!
