### ISSUE TITLE
Add alpine armv7 images

### ISSUE THREAD

**Issue by ncopa** [lxc/lxc-ci#740]
Currently the only available arm32 images for alpine are armhf, which is armv6 and only exist due to Raspberry pi 1 and zero.

Would be nice to have armv7 also.

**Comment by monstermunchkin** [comment]
We already have both arm32 and arm64 images for all alpine releases: https://images.linuxcontainers.org/

**Comment by ncopa** [comment]
The problem is that the arm32 image is armv6 and not armv7.
