### ISSUE TITLE
Ubuntu VM images using old kernel configuration?

### ISSUE THREAD

**Issue by jsoriano** [lxc/lxc-ci#752]
We have found that kernels in Ubuntu VM images are not built with `CONFIG_KPROBE_EVENTS`, what seems weird because this config is set in other VMs and in other Ubuntu images.

Looking to the source, the `debootstrap` downloader is configured to `gutsy`: https://github.com/lxc/lxc-ci/blob/c64e0c546045c22006f653f42c29ddb1b0e27226/images/ubuntu.yaml#L6

Could it be that this is using such an old kernel configuration?

This can be checked with:
```
lxc launch --vm ubuntu:23.04 ubuntu-1
lxc exec ubuntu-1 bash
cat /boot/config-$(uname -r) | grep CONFIG_KPROBE_EVENTS
```

In my Ubuntu 22.04 host the config file has 11785 lines, but in the 23.04 VM it has 3993.

**Comment by simondeziel** [comment]
FWI, lxc-ci is what's used to build images that are available from the `images:` remote. In your example, you are pulling from `ubuntu:` which is maintained by the Ubuntu Cloud team at Canonical. By default, VM images from `ubuntu:` use the `linux-kvm` package which is a  which is a special kernel flavor tailored for KVM VMs. It's been known to be missing quite a few features/modules in the past.

You have at least 2 options:

1. Report a bug against `linux-kvm` asking for this config key to be enabled (https://bugs.launchpad.net/ubuntu/+source/linux-kvm)
2. Switch to `linux-virtual` (or `linux-image-virtual`) that has `CONFIG_KPROBE_EVENTS=y` already

**Comment by jsoriano** [comment]
Thanks for your quick answer!

> Switch to `linux-virtual` (or `linux-image-virtual`) that has `CONFIG_KPROBE_EVENTS=y` already

How would I use these `linux-virtual` images with LXC?

**Comment by simondeziel** [comment]
If you stick to `ubuntu:` provided images, you need to install the `linux-virtual` package (and maybe remove the `linux-kvm` one) after launching the VM and reboot onto the new kernel.

Alternatively, you can switch to a community provided VM image (`lxc launch --vm images:ubuntu/23.04 ubuntu-1`) and you'll have the right kernel as those ship with `linux-image-virtual`.
