### ISSUE TITLE
images(ubuntu): jammy/default no longer contains templates to update hostname

### ISSUE THREAD

**Issue by MrDaGree** [lxc/lxc-ci#769]
I've only tested it with the Jammy default image, but it seems to no longer be including the needed templates in the lxd.tar.xz in order to update the hostname so the hostnames when launched is just `distrobuilder-XXXXX`

![image](https://github.com/lxc/lxc-ci/assets/5050898/cb3e5ed6-198a-4ae2-a30f-0489949ffbf7)

**Comment by kdrag0n** [comment]
Same issue with `ubuntu/lunar` for both arm64 and amd64.

```
❯ lxc launch images:ubuntu/lunar ul
Creating ul
Starting ul

❯ lxc shell ul
root@distrobuilder-b26c4c29-2463-4abf-815b-57ce2277a8c3:~#
```

**Comment by Thomas-Gelf** [comment]
I can confirm this for Bionic and Jammy. And as this output shows, it's related to the image, not to the lxc version:

```
root@srv:~# lxc image list
+----------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
|  ALIAS   | FINGERPRINT  | PUBLIC |              DESCRIPTION               | ARCHITECTURE |   TYPE    |   SIZE   |          UPLOAD DATE          |
+----------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
| bookworm | a6a9eb6eaa57 | no     | Debian bookworm amd64 (20230626_05:25) | x86_64       | CONTAINER | 94.05MB  | Jun 26, 2023 at 10:06pm (UTC) |
+----------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
| jammy    | 6784ba9da413 | no     | Ubuntu jammy amd64 (20230626_07:42)    | x86_64       | CONTAINER | 115.35MB | Jun 26, 2023 at 9:58pm (UTC)  |
+----------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
root@srv:~# lxc launch jammy a1
Creating a1
Starting a1                                 
root@srv:~# lxc shell a1
root@a1:~# halt
Session terminated, killing shell... ...killed.
root@srv:~# lxc image refresh jammy
Image refreshed successfully!                     
root@srv:~# lxc launch jammy a2
Creating a2
Starting a2
root@srv:~# lxc shell a2       
root@distrobuilder-2c3eb41e-14e8-465d-9877-df36f5d80922:~# 
```

**Comment by Thomas-Gelf** [comment]
![grafik](https://github.com/lxc/lxc-ci/assets/553008/91ef104d-235a-4ed7-bffb-afe710164e64)

NB: Updated the comment to show the image fingerprint/version in use after the refresh

**Comment by Thomas-Gelf** [comment]
(same goes true for debian images)

**Comment by monstermunchkin** [comment]
https://github.com/lxc/distrobuilder/pull/750

**Comment by monstermunchkin** [comment]
I'm closing this as I've reverted the broken commits. The new images should be fine again.

**Comment by monstermunchkin** [comment]
The bad commits broke all images. New images should be available by tomorrow.

**Comment by Thomas-Gelf** [comment]
Thanks for fixing this! As this potentially breaks quite some automation all over the world, would it be too bold to ask if the related build jobs could be kicked manually?

**Comment by MrDaGree** [comment]
I'd appreciate a manual kick of the builds too if possible
