### ISSUE TITLE
Permanently provide working image besides the latest three builds

### ISSUE THREAD

**Issue by Abdull** [lxc/lxc-ci#770]
With the recent [issue of several broken lxc images](https://github.com/lxc/lxc/issues/4325), I noticed that https://images.linuxcontainers.org/ / https://jenkins.linuxcontainers.org/ only keeps the latest three builds of an image.

E.g. as of this wiriting, for *debian/bullseye/arm64/default*:

* https://images.linuxcontainers.org/images/debian/bullseye/amd64/default/
  ![image](https://github.com/lxc/lxc-ci/assets/529862/4b4ad94b-24fc-453f-98dc-3219184c0e11)
* https://jenkins.linuxcontainers.org/job/image-debian/architecture=amd64,release=bullseye,variant=default/
  ![image](https://github.com/lxc/lxc-ci/assets/529862/3310fd84-6b82-48f4-a2cb-161e97539fd0)

As I understand the build setup, new images are built daily/nightly.

At day two during the broken builds phase, we were one day short of having no working images and losing build logs of previous _working_ images (which help with identifying the differences between working versus broken images).

I'm actually quite surprised (and relieved) that the aforementioned *broken images* issue didn't develop in an [*npm* `left-pad` situation](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code).

**Could *images.linuxcontainers.org* therefore permanently keep at least one working image version of each build configuration? This should only (... "only"?) require 33% more storage, and shouldn't add bandwidth, traffic, or compute costs.**

Thanks,
and thank you very much for lxc!

**Comment by stgraber** [comment]
Images are now only published to the image server once they pass automated testing.
