### ISSUE TITLE
default route not properly set on Centos 8 or 9 stream using routed nic

### ISSUE THREAD

**Issue by aivanise** [lxc/lxc-ci#776]
i was pointed here from https://github.com/canonical/lxd/issues/12099 so here goes:

when creating a centos instance with routed NIC, default route is not set and there is a funny network connection in network manager

it all works if the container is ubuntu 22.04

[root@gcpa ~]# lxd --version
5.15

```
[root@gcpa ~]# lxd init --dump
...
profiles:
- config:
  description: default profile
  devices:
    eth0:
      name: eth0
      nictype: routed
      type: nic
    root:
      path: /
      pool: ee
      type: disk
  name: default
projects:
- config:
    features.images: "true"
    features.networks: "true"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
  description: Default LXD project
  name: default


# lxc launch images:centos/9-Stream/cloud testa -d eth0,ipv4.address=172.18.1.4
Creating testa
Starting testa                              
[root@gcpa ~]# lxc exec testa -- bash -i
[root@testa ~]# ip r s
[root@testa ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
45: eth0@if46: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:33:e2:71 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.1.4/32 scope global eth0
       valid_lft forever preferred_lft forever
[root@testa ~]# nmcli conn show
NAME         UUID                                  TYPE      DEVICE 
lo           f6c6f50c-9416-425d-842e-484cedbb25d1  loopback  lo     
eth0         06c4fc6e-3383-4de0-9651-2f460d45ea20  ethernet  eth0   
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  --     

```

**Comment by stgraber** [comment]
Network Manager has a bit of a tendency to try to takeover everything on boot. That's fine for DHCP based setups but more of a problem with things like the routed NICs which rely on preconfigured state.

Can you try disabling the systemd unit and see if that does the trick?

**Comment by aivanise** [comment]
Disabled NetworkManager unit, no change. I have even created an image with NM disabled and created a container from that so that NM never ran, still the same, IP address is there but default route is not.

**Comment by stgraber** [comment]
Can you show `cat /var/snap/lxd/common/lxd/logs/testa/lxc.conf`?

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ lxc exec foo bash
[root@foo ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
4150: eth0@if4151: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default qlen 1000 link-netnsid 0
    inet 172.18.1.4/32 scope global eth0
       valid_lft forever preferred_lft forever
[root@foo ~]# ip -4 r
[root@foo ~]# ps fauxww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         182  0.0  0.0   7832  2816 pts/1    Ss   16:31   0:00 bash
root         250  0.0  0.0  10532  1920 pts/1    R+   16:31   0:00  \_ ps fauxww
root           1  0.0  0.0  21376  8064 ?        Ss   16:31   0:00 /sbin/init
root         121  0.0  0.0  26136  9728 ?        Ss   16:31   0:00 /usr/lib/systemd/systemd-journald
root         134  0.0  0.0  28064  5760 ?        Ss   16:31   0:00 /usr/lib/systemd/systemd-udevd
dbus         144  0.0  0.0  10792  2560 ?        Ss   16:31   0:00 /usr/bin/dbus-broker-launch --scope system --audit
dbus         145  0.0  0.0   4992  1664 ?        S    16:31   0:00  \_ dbus-broker --log 4 --controller 9 --machine-id d4b9c49fc9cf41f7983fde8b709bad07 --max-bytes 536870912 --max-fds 4096 --max-matches 131072 --audit
root         148  0.0  0.0  17920  5632 ?        Ss   16:31   0:00 /usr/lib/systemd/systemd-logind
root         158  0.0  0.0  17664  5760 ?        Ss   16:31   0:00 /usr/lib/systemd/systemd-hostnamed
root         160  0.0  0.0 256568 11520 ?        Ssl  16:31   0:00 /usr/sbin/NetworkManager --no-daemon
root         164  0.0  0.0 237600  5504 ?        Ssl  16:31   0:00 /usr/libexec/nm-dispatcher
root         219  0.0  0.0 163916  3628 ?        Ssl  16:31   0:00 /usr/sbin/rsyslogd -n
root         222  0.0  0.0   5648  1024 pts/0    Ss+  16:31   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud - 115200,38400,9600 linux
root         223  0.0  0.0   8580  2304 ?        Ss   16:31   0:00 /usr/sbin/crond -n
root         232  0.0  0.0  15792  5888 ?        Ss   16:31   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
[root@foo ~]# systemctl -a | grep -i network
  cloud-init-local.service               loaded    active   exited    Initial cloud-init job (pre-networking)
  import-state.service                   loaded    inactive dead      Import network configuration from initramfs
  network-device-down.service            loaded    active   exited    Turn off network device
● network.service                        not-found inactive dead      network.service
  NetworkManager-wait-online.service     loaded    active   exited    Network Manager Wait Online
  NetworkManager.service                 loaded    active   running   Network Manager
  nis-domainname.service                 loaded    active   exited    Read and set NIS domainname from /etc/sysconfig/network
  systemd-network-generator.service      loaded    active   exited    Generate network units from Kernel command line
● systemd-networkd-wait-online.service   not-found inactive dead      systemd-networkd-wait-online.service
● systemd-networkd.service               not-found inactive dead      systemd-networkd.service
  network-online.target                  loaded    active   active    Network is Online
  network-pre.target                     loaded    active   active    Preparation for Network
  network.target                         loaded    active   active    Network
[root@foo ~]# systemctl mask NetworkManager
Created symlink /etc/systemd/system/NetworkManager.service → /dev/null.
[root@foo ~]# systemctl mask NetworkManager-wait-online
Created symlink /etc/systemd/system/NetworkManager-wait-online.service → /dev/null.
[root@foo ~]# systemctl mask network-device-down
Created symlink /etc/systemd/system/network-device-down.service → /dev/null.
[root@foo ~]# reboot
[root@foo ~]# 
stgraber@dakara:~$ lxc exec foo bash
[root@foo ~]# ip -4 r
default via 169.254.0.1 dev eth0 
169.254.0.1 dev eth0 scope link 
[root@foo ~]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
4152: eth0@if4153: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 link-netnsid 0
    inet 172.18.1.4/32 scope global eth0
       valid_lft forever preferred_lft forever
[root@foo ~]# 
```

**Comment by stgraber** [comment]
The culprit is `network-device-down` which is a systemd unit injected in images that use NetworkManager to have it properly handle the network devices (for DHCP).

**Comment by aivanise** [comment]
> The culprit is `network-device-down` which is a systemd unit injected in images that use NetworkManager to have it properly handle the network devices (for DHCP).

Wouldn't it be nice if centos(es) work out of the box no matter what the config is? Can you maybe detect a routed interface and not generate that unit in that case? Maybe if a default route is already pointing to 169.254.0.1 then it must be a routed, or maybe some more elegant way?

**Comment by stgraber** [comment]
It certainly would be nice, but I don't know the first thing about CentOS and the combination of the userbase of the CentOS image and of LXD routed NICs is so low that it's not really worth me spending hours trying to change this, potentially risking breaking the much much larger userbase of normal DHCP users.

All the image build tooling is open source though so you can try editing the systemd generator script in the image to have it do the right thing for you, validate that this doesn't break regular setups and then contribute your change to distrobuilder.

https://github.com/lxc/distrobuilder/blob/7e61e2e6997d0691c2182cd75ecc6228980056ad/distrobuilder/main.go#L609 is where the code in question resides. Do keep in mind that this particular script must work properly inside:
 - LXC unprivileged containers
 - LXC privileged containers
 - LXD unprivileged containers
 - LXD privileged containers
 - LXD virtual machines
 - Proxomox containers
And that the exact same script is run on all Linux distributions and all releases, so it needs to be very careful about calling commands as those may not exist on some distros or may be located in a different location.

**Comment by aivanise** [comment]
fair enough, how about this, only one line:

`--- /tmp/lxc.orig       2023-08-02 06:19:32.456191823 +0000
+++ /etc/systemd/system-generators/lxc  2023-08-02 06:37:43.411685196 +0000
@@ -57,6 +57,8 @@
 Before=NetworkManager.service
 Before=systemd-networkd.service
 [Service]
+# do not turn off if there is a default route to 169.254.0.1, i.e. the device is routed nic
+ExecCondition=/bin/sh -c '! /usr/bin/grep -qs 00000000.0100FEA9 /proc/net/route'
 ExecStart=-${ip_path} link set $1 down
 Type=oneshot
 RemainAfterExit=true
`

it only depends on (ba)sh and grep and since this code is only run when there is NetworkManager present, it is a fairly safe assumption the grep will be there too, and even if it isn't it will err on the side of caution, i.e. any error is true, even the lack of grep or /proc/net/route. sh is definitely already there since the generator is run in it.

I have tested it in streams 8 and 9, not sure which other distros have NetworkManager, but I can test there too

**Comment by aivanise** [comment]
https://github.com/lxc/distrobuilder/pull/758
