### ISSUE TITLE
Missing Fedora Rawhide images

### ISSUE THREAD

**Issue by kdrag0n** [lxc/lxc-ci#777]
I noticed that the Fedora Rawhide images were removed in e825094b399e3d62d6df117d35e1739618a582c2, and the last builds are no longer available on images.linuxcontainers.org. Is there any reasoning behind this change?

**Comment by stgraber** [comment]
Yeah, we normally don't build development releases.
We do have two exceptions currently, Ubuntu and Debian, but both of those heavily gate their development releases therefore preventing package install conflicts during migrations.

Apparently Fedora doesn't do that as we had broken images for pretty much an entire week until I removed rawhide from the set we're attempting to build. As we publish images as a full set, we can't afford to have flaky releases for a given distro.

**Comment by kdrag0n** [comment]
Got it, thanks for the insight.
