### ISSUE TITLE
Cannot create custom gentoo images with latest gentoo.yaml file

### ISSUE THREAD

**Issue by listout** [lxc/lxc-ci#792]
With the latest gentoo.yaml file and distrobuilder 2.1 I'm getting the following error:
```
>> sudo distrobuilder build-lxd ../gentoo.yaml -o image.architecture=amd64 -o image.variant=openrc -o source.variant=llvm-openrc
Error: Failed to get definition: files.*.generator must be one of [dump copy template hostname hosts remove upstart-tty cloud-init lxd-agent fstab]
INFO[2023-10-31T23:35:52+05:30] Removing cache directory
```

Getting gentoo.yaml from commit 37ec1ef974b2630e6948585e0614be2bee746cf0 fixes the issue. Not really sure what exactly changed in bf2d36647c15aa8799204949c5d687879cc72636 to give this error.

Feel free to ping if more info is needed. Thanks.

**Comment by monstermunchkin** [comment]
I believe the issue was `lxd-agent` which has since been renamed to `incus-agent`.

**Comment by stgraber** [comment]
Indeed, either you need to use distrobuilder from edge or you need to replace incus-agent with lxd-agent in your YAML.

**Comment by listout** [comment]
Thanks @monstermunchkin and @stgraber.
