### ISSUE TITLE
Add alpine 3.19

### ISSUE THREAD

**Issue by melato** [lxc/lxc-ci#803]
Could you add 3.19 to images:?

alpine 3.19 was released on 2023-12-07: https://alpinelinux.org/posts/Alpine-3.19.0-released.html

I think it just needs to be added to jenkins/jobs/image-alpine.yaml, in the axis with name: release.
But 3.18 is also used further down this file:
```
EXTRA_ARGS=""                                                                                                        
        if [ "${release}" = "edge" ]; then                                                                                   
            EXTRA_ARGS="-o source.same_as=3.18"                                                                              
        fi       
```
I don't know if that should change to 3.19.

I built alpine/3.19 using distrobuilder and I am already using it on amd64 and arm64.
I built it because alpine 3.19 had the fix for the openssh terrapin vulnerability, but alpine 3.18 didn't.
In the meantime that fix is also in alpine 3.18:  https://gitlab.alpinelinux.org/alpine/aports/-/issues/15593

**Comment by stgraber** [comment]
Yeah, that second chunk in the hall YAML should be changed to. I think we always want edge to be based on the latest stable.
