### ISSUE TITLE
Fixing ubuntu noble build failure

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxc-ci#816]
Hey @stgraber 

I saw that you fixed the noble build on the CI. I was getting the same error here https://jenkins.linuxcontainers.org/job/image-ubuntu/architecture=arm64,release=noble,variant=cloud/3246/console 

If you could share how this was resolved it would be much appreciated.

Thank you!

**Comment by stgraber** [comment]
Distrobuilder was updated with a workaround.

**Comment by zacksiri** [comment]
Thank you, it's all working now!
