### ISSUE TITLE
openSUSE images missing

### ISSUE THREAD

**Issue by kdrag0n** [lxc/lxc-ci#824]
It looks like the openSUSE images were removed last week, but the CI builds seem to be succeeding: https://jenkins.linuxcontainers.org/job/image-opensuse/

Any insights?

**Comment by stgraber** [comment]
The build is succeeding but the tests are not, so they've been held back from publishing, eventually causing the images we do have to expire.

I'll take another look at what's going on with those images to try to unstick things.

**Comment by kdrag0n** [comment]
Got it, thanks for clarifying!

**Comment by stgraber** [comment]
I'm looking into the test failure now.

**Comment by stgraber** [comment]
I've excluded the problematic image (cloud-init crashes on OpenSUSE 15.5 cloud) and the rest is publishing again now.

**Comment by kdrag0n** [comment]
Looks good now, thanks for the quick fix!
