### ISSUE TITLE
Force-restart Jenkins

### ISSUE THREAD

**Issue by dimitry-unified-streaming** [lxc/lxc-ci#830]
Looks like https://jenkins.linuxcontainers.org/job/incus-test-usb/245/ has been hanging for ~20 hours now, endlessly repeating:

```text
===> System is currently busy, trying again in 60s
===> System is currently busy, trying again in 60s
===> System is currently busy, trying again in 60s
```

And this seems to be holding up any other jobs from starting. Maybe this job should be canceled, so Jenkins can be restarted?

**Comment by stgraber** [comment]
Should be getting unblocked soon, the machine in question was used for some manual work, so it was expected that Jenkins would be waiting on it.
