### ISSUE TITLE
Config can no longer be rebuilt on containers derived from latest NixOS images

### ISSUE THREAD

**Issue by srd424** [lxc/lxc-ci#831]
See https://github.com/lxc/lxc-ci/commit/78affff15873b3212c4567675e9206415e41ffae#r142633020 - this change renamed `/etc/nixos/lxd.nix` to `incus.nix`, but `/etc/nixos/configuration.nix` is generated upstream and seems to still refer to the old name:

https://github.com/NixOS/nixpkgs/blob/77c97942c072a6d9ed5fc7790b607b3cfad6784b/nixos/maintainers/scripts/lxd/lxd-container-image-inner.nix#L13

**Comment by srd424** [comment]
Would recommend reverting this one single change for now and then playing rock, paper, scissors with upstream :)

**Comment by stgraber** [comment]
Thanks!
