### ISSUE TITLE
[OT] How can I setup my own lxc-ci server? Or how to import the jobs files to Jenkins?

### ISSUE THREAD

**Issue by levindu** [lxc/lxc-ci#845]
Hi folks,

I'm rather interested in the setup of lxc-ci server, especially the import of the jobs/views file (in yaml format) into Jenkins server.

Would anyone point me out the plugin or scripts to do that?

**Comment by stgraber** [comment]
https://jenkins-job-builder.readthedocs.io/en/latest/
