### ISSUE TITLE
Kali `cloud` builds failing

### ISSUE THREAD

**Issue by kdrag0n** [lxc/lxc-ci#849]
Kali `cloud` builds have been failing for 17 days, causing the image to get removed:

```
+ systemctl enable cloud-init
Failed to enable unit: Unit cloud-init.service does not exist
Error: Failed to run post-packages: exit status 1
```

It looks like the init script is now `cloud-init-main` (or everything was moved to `cloud-init.target`?):

```
update-rc.d: We have no instructions for the cloud-init-main init script.
update-rc.d: It looks like a non-network service, we enable it.
Created symlink '/etc/systemd/system/cloud-init.target.wants/cloud-config.service' → '/usr/lib/systemd/system/cloud-config.service'.
Created symlink '/etc/systemd/system/cloud-init.target.wants/cloud-final.service' → '/usr/lib/systemd/system/cloud-final.service'.
Created symlink '/etc/systemd/system/cloud-init.target.wants/cloud-init-local.service' → '/usr/lib/systemd/system/cloud-init-local.service'.
```

Is the `systemctl enable` necessary given that the services seem to be getting auto-enabled during installation?

**Comment by winterqt** [comment]
Also: despite the `default` variant succeeding, it seems that the `cloud` variant's failure/removal is causing the `default` variant to also be removed.

**Comment by stgraber** [comment]
A fix was pushed now and images are building once again.
