### ISSUE TITLE
debian and ubuntu containers cloud container doesnt have openssh-server installed

### ISSUE THREAD

**Issue by Sloopy3333** [lxc/lxc-ci#851]
Debian and Ubuntu container images doesn't have openssh-server installed, this makes them harder to configure through ansible.

**Comment by stgraber** [comment]
That's intentional. We don't want to have services listening on the network in our default images.

**Comment by stgraber** [comment]
Just pushed a commit to remove openssh-server from those images, not sure how it got in there :)

It's possible that cloud-init was failing to run without openssh-server at some point in time, not too sure. Anyway, the next image builds won't have openssh-server anymore and we'll see if that affects our automatic tests.
