### ISSUE TITLE
OpenSUSE Tumbleweed desktop-kde doesn't launch

### ISSUE THREAD

**Issue by UTsweetyfish** [lxc/lxc-ci#855]
Hi,

When using the `opensuse/tumbleweed/desktop-kde` vm image, the virtual machine launches successfully, but sddm can't start.

From `journalctl -u sddm.service`, the following error is given:

```
Nov 20 05:29:27 tw-kde systemd[1]: Started Simple Desktop Display Manager.
Nov 20 05:29:27 tw-kde sddm[1353]: Initializing...
Nov 20 05:29:27 tw-kde sddm[1353]: Starting...
Nov 20 05:29:27 tw-kde sddm[1353]: Logind interface found
Nov 20 05:29:27 tw-kde sddm[1353]: Adding new display...
Nov 20 05:29:27 tw-kde sddm[1353]: Loaded empty theme configuration
Nov 20 05:29:27 tw-kde sddm[1353]: Xauthority path: "/run/sddm/xauth_GOLsMf"
Nov 20 05:29:27 tw-kde sddm[1353]: Using VT 2
Nov 20 05:29:27 tw-kde sddm[1353]: Unable to find autologin session entry "default.desktop"
Nov 20 05:29:27 tw-kde sddm[1353]: Display server starting...
Nov 20 05:29:27 tw-kde sddm[1353]: Writing cookie to "/run/sddm/xauth_GOLsMf"
Nov 20 05:29:27 tw-kde sddm[1353]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt2 -auth /run/sddm/xauth_GOLsMf -noreset -displayfd 16
Nov 20 05:29:27 tw-kde sddm[1353]: Failed to start display server process.
Nov 20 05:29:27 tw-kde sddm[1353]: Attempt 1 starting the Display server on vt 2 failed
```

The error seems to be related to the absence of `default.desktop` in the directory `/usr/share/wayland-sessions/`, while a file named `plasmawayland.desktop` is present there.

I tried running `ln -s default.desktop plasmawayland.desktop` and restart sddm, Plasma starts successfully.

**Comment by stgraber** [comment]
Hmm, that's odd, I'm not very familiar with OpenSUSE but that sounds like something that wouldn't just impact us but anyone installing KDE, no?

**Comment by UTsweetyfish** [comment]
> Hmm, that's odd, I'm not very familiar with OpenSUSE but that sounds like something that wouldn't just impact us but anyone installing KDE, no?

https://github.com/lxc/lxc-ci/blob/2a6c9cdef744c05bec739bbdde94e486308831ee/images/opensuse.yaml#L183

We have a variant `desktop-kde` for openSUSE Tumbleweed, and it's expected to start sddm and autostart KDE6.

https://github.com/lxc/lxc-ci/blob/2a6c9cdef744c05bec739bbdde94e486308831ee/images/opensuse.yaml#L190

The problem is that in the current image, the `default.desktop` no longer exists, but a `plasmawayland.desktop` is present.

**Comment by stgraber** [comment]
Okay, so the better fix is to make it so on tumbelweed, `autologin.conf` sets `Session=plasmawayland` instead of `Session=default`
