### ISSUE TITLE
Debian MIPS images

### ISSUE THREAD

**Issue by jcowgill** [lxc/lxc-ci#9]
Is it possible for LXC to build Debian mips\* images now that they work properly (at least with the dev version of LXC)?

The arches are mips, mipsel and mips64el although mips64el only exists in stretch and sid.

**Comment by stgraber** [comment]
Not very easily, no. The CI infrastructure that builds those images runs on the native architecture (see jenkins.linuxcontainers.org). We do have fast builders for all the other architectures, but not for any of the mips stuff.

**Comment by jcowgill** [comment]
Ah I didn't know everything was built natively. Using QEMU works (the `-I` option to the lxc-debian template), but if that's not good enough I don't think there are any options left.

**Comment by stgraber** [comment]
Yeah, this may be a bit tricky to do even with a VM because we need to setup a full Jenkins builder in there and I'm not sure what kind of performance we'd be getting from running the big Jenkins java runner inside such a VM :)

**Comment by jcowgill** [comment]
I mean qemu-user. You install it on the host and then pass `-I /usr/bin/qemu-mips64el-static` (or something similar) to `lxc-create` and it will use qemu to build the image.

**Comment by stgraber** [comment]
Ah yeah, we could add support for qemu-user-static to the lxc-ci code and then have it build using the two stage --foreign debootstrap option that lxc-debian already supports.

**Comment by stgraber** [comment]
Closing this here as we're entirely relying on distrobuilder for image building now.
If you want to contribute qemu-user-static support to distrobuilder for Debian images, then we could add the MIPS images.

https://github.com/lxc/distrobuilder

**Comment by advancedwebdeveloper** [comment]
@jcowgill , do you have any progress here?
