### ISSUE TITLE
Centos 8 container doesn't always get IPv4 address from DHCP 

### ISSUE THREAD

**Issue by cquike** [lxc/lxc-ci#90]
I am starting to deploy Centos 8 LXD containers and I see that most of the time the container doesn't get an IPv4 address. it seems to be a race condition, because in a fairly fast host with an SSD it gets the address most of the time while in a slower host it doesn't get it most of the time.

The containers where created with the simple command
`lxc init images:centos/8 centos8-test`

I am not sure whether this is a problem of Centos 8 itself or LXD.

**Comment by cquike** [comment]
This is the output of journalctl in the case where no IPv4 address is set:

> Oct 14 16:56:27 centos8-test systemd[1]: Starting Network Manager Script Dispatcher Service...
Oct 14 16:56:27 centos8-test systemd[1]: Started Network Manager Script Dispatcher Service.
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2902] settings: Loaded settings plugin: SettingsPluginIfcfg ("/usr/lib64/NetworkManager/1.14.0-14.el8/libnm-settings-plugin-ifcfg-rh.so")
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2909] settings: Loaded settings plugin: NMSIbftPlugin ("/usr/lib64/NetworkManager/1.14.0-14.el8/libnm-settings-plugin-ibft.so")
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2909] settings: Loaded settings plugin: NMSKeyfilePlugin (internal)
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2939] ifcfg-rh: new connection /etc/sysconfig/network-scripts/ifcfg-eth0 (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03,"System eth0")
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2962] manager: rfkill: WiFi enabled by radio killswitch; enabled by state file
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2964] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2965] manager: Networking is enabled by state file
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2967] dhcp-init: Using DHCP client 'internal'
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2981] device (lo): carrier: link connected
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2986] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.2998] device (eth0): carrier: link connected
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3001] manager: (eth0): new Veth device (/org/freedesktop/NetworkManager/Devices/2)
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3034] ifcfg-rh: add connection in-memory (557db903-6fc0-4a9f-b6d2-219fbbd46258,"eth0")
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3040] device (eth0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3056] device (eth0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3069] device (eth0): Activation: starting connection 'eth0' (557db903-6fc0-4a9f-b6d2-219fbbd46258)
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3098] device (eth0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3105] device (eth0): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3110] device (eth0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3114] device (eth0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3123] device (eth0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3126] device (eth0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3132] manager: NetworkManager state is now CONNECTED_LOCAL
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3139] device (eth0): Activation: successful, device activated.
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3145] manager: NetworkManager state is now CONNECTED_GLOBAL
Oct 14 16:56:27 centos8-test NetworkManager[56]: <info>  [1571072187.3151] manager: startup complete
Oct 14 16:56:27 centos8-test systemd[1]: Started Network Manager Wait Online.
Oct 14 16:56:27 centos8-test systemd[1]: Reached target Network is Online.


In the case the address is set the log looks like this:

>   Oct 14 16:56:24 centos8-test systemd[1]: Starting Network Manager Script Dispatcher Service...
Oct 14 16:56:24 centos8-test systemd[1]: Started Network Manager Script Dispatcher Service.
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9241] settings: Loaded settings plugin: SettingsPluginIfcfg ("/usr/lib64/NetworkManager/1.14.0-14.el8/libnm-settings-plugin-ifcfg-rh.so")
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9247] settings: Loaded settings plugin: NMSIbftPlugin ("/usr/lib64/NetworkManager/1.14.0-14.el8/libnm-settings-plugin-ibft.so")
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9248] settings: Loaded settings plugin: NMSKeyfilePlugin (internal)
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9267] ifcfg-rh: new connection /etc/sysconfig/network-scripts/ifcfg-eth0 (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03,"System eth0")
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9289] manager: rfkill: WiFi enabled by radio killswitch; enabled by state file
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9290] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9291] manager: Networking is enabled by state file
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9292] dhcp-init: Using DHCP client 'internal'
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9304] device (lo): carrier: link connected
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9306] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9312] device (eth0): carrier: link connected
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9314] manager: (eth0): new Veth device (/org/freedesktop/NetworkManager/Devices/2)
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9328] device (eth0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9376] device (eth0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9384] policy: auto-activating connection 'System eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9410] device (eth0): Activation: starting connection 'System eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9413] device (eth0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9416] manager: NetworkManager state is now CONNECTING
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9418] device (eth0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9422] device (eth0): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:24 centos8-test NetworkManager[55]: <info>  [1571072184.9426] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2956] dhcp4 (eth0):   address 10.196.184.81
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2957] dhcp4 (eth0):   plen 24
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2957] dhcp4 (eth0):   expires in 3600 seconds
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2958] dhcp4 (eth0):   nameserver '10.196.184.1'
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2958] dhcp4 (eth0):   domain name 'lxd'
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2958] dhcp4 (eth0):   hostname 'centos8-test'
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2958] dhcp4 (eth0):   gateway 10.196.184.1
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2960] dhcp4 (eth0): state changed unknown -> bound
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2972] device (eth0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2982] device (eth0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2985] device (eth0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2989] manager: NetworkManager state is now CONNECTED_LOCAL
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2996] manager: NetworkManager state is now CONNECTED_SITE
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.2997] policy: set 'System eth0' (eth0) as default for IPv4 routing and DNS
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.3000] policy: set 'System eth0' (eth0) as default for IPv6 routing and DNS
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.3004] device (eth0): Activation: successful, device activated.
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.3011] manager: NetworkManager state is now CONNECTED_GLOBAL
Oct 14 16:56:28 centos8-test NetworkManager[55]: <info>  [1571072188.3020] manager: startup complete
Oct 14 16:56:28 centos8-test systemd[1]: Started Network Manager Wait Online.
Oct 14 16:56:28 centos8-test systemd[1]: Reached target Network is Online.

**Comment by stgraber** [comment]
@cquike can you check if `images:centos/8/cloud` gives you the same problem?

We have a NetworkManager override in that one which may be working around this issue, if that one works, we can roll out that workaround to more images.

**Comment by cquike** [comment]
Hi,
I have done now some tests with your suggestion and indeed now I have not seen any cases in which the container doesn't get the IPv4 address. So it looks like the workaround is working! It would be great if it can be rolled out to the other images.

**Comment by cquike** [comment]
Just for the record: the images:centos/8 images seem to work fine now.
Thank you!

**Comment by christoph-conrads** [comment]
This issue occurs for me when several containers are started within a short amount of time and I see the exact same log output in `/var/log/messages`. The critical difference seems to be the initialization of the NIC. Please reopen the issue.

* [messages.c8-2.txt](https://github.com/lxc/lxc-ci/files/6326628/messages.c8-2.txt)
* [messages.c8-3.txt](https://github.com/lxc/lxc-ci/files/6326630/messages.c8-3.txt)
* LXD 4.0.5 on Ubuntu 20.04 (amd64)

Container without IPv4 address and with domain name resolution problems:
```
device (eth0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
device (eth0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
device (eth0): Activation: starting connection 'eth0' (7531d6d2-c2e2-4b25-9c69-8b27c7204009)
```
Container with IPv4 address and without DNS problems:
```
device (eth0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
device (eth0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
policy: auto-activating connection 'System eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
```

The issue can be triggered with the following script:
```sh
#!/bin/bash

set -e
set -u

CONTAINER_ID="${1:?container identifier needed}"

if $(lxc info "$CONTAINER_ID" >/dev/null 2>/dev/null); then
	lxc stop -- "$CONTAINER_ID"
	lxc delete -- "$CONTAINER_ID"
fi

lxc launch 'images:centos/8' "$CONTAINER_ID"

for i in $(seq 1 10); do
	if lxc exec "$CONTAINER_ID" -- sh -c "systemctl isolate multi-user.target" >/dev/null 2>/dev/null; then
		break
	fi
	echo "waiting for $CONTAINER_ID to finish booting..."
	sleep 1s
done

set +e
lxc exec "$CONTAINER_ID" -- /bin/bash <<EOF
echo host $CONTAINER_ID \$(ping -c 1 github.com 2>&1 >/dev/null)
EOF
```
Script call:
```sh
for i in $(seq 1 4); do
	cid="c8-$i"
	bash run-centos8.sh "$cid" &
done
```
Output:
```
Creating c8-2
Creating c8-1
Starting c8-4                             
Remapping container filesystemCreating c8-3
Starting c8-2                             
Starting c8-1
Starting c8-3                             
host c8-4                      
host c8-1 ping: github.com: Name or service not known
host c8-2 ping: github.com: Name or service not known
host c8-3
```
DNS broke in c8-1, c8-2; DNS is working in c8-3, c8-4. These are symptoms of missing IPv4 addresses:
```
$ lxc exec c8-2 -- nmcli con show
NAME         UUID                                  TYPE      DEVICE 
eth0         7531d6d2-c2e2-4b25-9c69-8b27c7204009  ethernet  eth0   
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  --     
$ lxc exec c8-3 -- nmcli con show
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
$ lxc exec c8-2 -- ip addr show dev eth0
110: eth0@if111: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:7d:0f:60 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fd42:e539:483d:a423:216:3eff:fe7d:f60/64 scope global dynamic mngtmpaddr 
       valid_lft 3156sec preferred_lft 3156sec
    inet6 fe80::216:3eff:fe7d:f60/64 scope link 
       valid_lft forever preferred_lft forever
$ lxc exec c8-3 -- ip addr show dev eth0
114: eth0@if115: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:ba:00:58 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.208.123.6/24 brd 10.208.123.255 scope global dynamic noprefixroute eth0
       valid_lft 3076sec preferred_lft 3076sec
    inet6 fd42:e539:483d:a423:216:3eff:feba:58/64 scope global dynamic noprefixroute 
       valid_lft 3152sec preferred_lft 3152sec
    inet6 fe80::216:3eff:feba:58/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
